### ISSUE TITLE
Players getting unadded from plots if they change their username

### ISSUE THREAD

**Issue by VoxaDub** [IntellectualSites/PlotSquared#1041]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**: http://hastebin.com/jogazoqane

**Description of the problem:**  people noticed some of the people they added or trusted got removed and replaced with ''Unknown'' and now if they change their IGNs then they lose their own plot completely

**How to replicate**: own a plot and add/trust people to your plot and see if they get replaced with unknown. Or own a plot and change your name.

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
What Minecraft version are you using? it is coming up as 0.0.0 in your debugpaste.

**Comment by boy0001** [comment]
online_mode: com.plotsquared.bukkit.uuid.OfflineUUIDWrapper@5a642f72;false
Server is in offline mode.

**Comment by VoxaDub** [comment]
I am on 1.8.8 and the server is not in offline mode.
http://i.imgur.com/rOqelVR.png

**Comment by manuelgu** [comment]
@VoxaDub would you mind sharing a full startup log of your server?

**Comment by MattBDev** [comment]
@VoxaDub You are 2 versions behind. Update to [3.3.3](https://github.com/IntellectualSites/PlotSquared/releases/download/v3.3.3/PlotSquared-Bukkit.jar)

**Comment by boy0001** [comment]
Wouldn't be fixed by updating. @VoxaDub Are you using bungee by any chance. Do you have ip_forward enabled?

**Comment by VoxaDub** [comment]
I have updated to the latest one here is the latest debugpaste 
http://hastebin.com/izifilixog

and its not on bungee

**Comment by boy0001** [comment]
@VoxaDub 
>  Also attaching your server jar would be useful since the version is 0,0,0

**Comment by boy0001** [comment]
Workaround in latest commit.
@VoxaDub 
Can you either provide the full startup log or your server jar?

**Comment by VoxaDub** [comment]
boy0001 I have emailed you the logs and server jar.
and i have updated to the latest version and now /plot unclaim is showing as though its not a command...?

**Comment by boy0001** [comment]
Yeah, it's not.
Use one of the following
/plot delete
/plot setowner none
/plot purge id=<id> world=<world>

**Comment by VoxaDub** [comment]
Why on earth would you remove the command...?
Everyone uses /plot unclaim....

**Comment by MattBDev** [comment]
Is this still an issue? I don't receive a reply soon, I will be closing this.

**Comment by crashtheparty** [comment]
I am having this issue on 1.10.2 (at least the name change issue). Using Bungeecord and ip forwarding. 

It seems like they can still build in their own plots, but the names don't update on the welcome text and they are no longer allowed to add or trust people on their plots.

Cannot send a debug command link because there is an error when I use the command:

03.06 23:37:41 [Server] WARN [PlotSquared] Plugin PlotSquared v3.5.0-SNAPSHOT-95f8aaa generated an exception while executing task 38920164
03.06 23:37:41 [Server] INFO java.lang.RuntimeException: Couldn't read response!
03.06 23:37:41 [Server] INFO at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:43) ~[?:?]
03.06 23:37:41 [Server] INFO at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60) ~[?:?]
03.06 23:37:41 [Server] INFO at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29) ~[?:?]
03.06 23:37:41 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.jar:git-Spigot-de459a2-51263e9]
03.06 23:37:41 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.10.jar:git-Spigot-de459a2-51263e9]
03.06 23:37:41 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
03.06 23:37:41 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
03.06 23:37:41 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

Latest version of Plot Squared is enabled.

**Comment by dordsor21** [comment]
Using latest version from http://ci.athion.net/job/PlotSquared ?
