### ISSUE TITLE
Roads Regeneration Glitch (Roads Spawning With Incorrect Blocks)

### ISSUE THREAD

**Issue by RayDaAsian** [IntellectualSites/PlotSquared#1182]
http://hastebin.com/iruhuqofuv

A year ago, I began using PlotSquared for my prison server. It worked flawlessly, but there was one problem; roads would generate incorrectly, usually generating blocks other than the blocks specified in the schematics. Most of the time the blocks that would spawn are just random variants of the blocks. For example, if it was Andesite (1:5), it would generate maybe Diorite (1:3) or just plain stone. Roads with clay would generate with random colors, and rarely does it even spawn just random blocks. 

I took a break and a year later I'm back using the same plugin, I've seen the drastic improvements the plugin has undergone, however I still have this same issue. No one else seems to be or have experienced my issue. I have been using the command "regenallroads" to fix the problem, but the glitched roads seems to happen randomly and it varies. I use the command "debugroadregen" on the glitched spots and it regenerates the road correctly. 
- Roads regenerate accordingly with the schematic, but patches of glitched blocks begin to spawn randomly.
- These glitched spots can vary from 3-4 blocks or to infinity
- regenallroads fixes the problem, but the glitched spots appear randomly once again

**Creative Server Roads: http://prntscr.com/bgnhy1**
As you can see the roads on the top are perfectly fine, however the bottom portion is...f*****\* up.

**Prison Server Roads:http://prntscr.com/bgnl7g (how it should look like), http://prntscr.com/bgnkrw (glitched)**
These set of roads are on a totally different server and were setup a year ago. This plotworld seems to have glitched spots appear in new chunks, farther away from the original spawn of the plotworld.

Is it a chunk loading issue? 
**How to replicate**: Regenerate roads using schematics. Fly around and let chunks load, they should appear randomly.

I apologize for the lengthy explanation, but I hope it's sufficient enough to provide a solution for me ASAP!

~RayDaAsian
mc.thehyperbeast.net
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)]
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by dadus33** [comment]
I've got a rather similar issue. I created a plot world using /plot setup. Then, I chose a plot and edited the road around it so it looked the way I wanted. I then used /p createroadschematic with FAWE installed, but I ran into an issue in the console: http://hastebin.com/givofocasa.avrasm
I uninstalled FAWE and tried with just using worldedit. But that turned out to glitch everything... To see what I mean, here's a pic:
https://gyazo.com/54e9c589136dec244139ccb7c1c594ff
However, the stairs seem to be the only ones that get messed up. I can't reproduce the issue described by @RayDaAsian with other blocks such as clay, wood or slabs. Those are pasted just fine.
PS: I'm using paperspigot 1.9.4, latest successful build of FAWE and latest successful build of PlotSquared. I've also tried playing with the version but always got the same result. As for worldedit, I'm using the latest version from the master branch: http://builds.enginehub.org/job/worldedit/9158
I hope you'll be able to fix this issue!
