### ISSUE TITLE
overlaping after update

### ISSUE THREAD

**Issue by random1167** [IntellectualSites/PlotSquared#1188]
![90j5q645](https://cloud.githubusercontent.com/assets/13611085/16108368/0ed227b4-33e6-11e6-8214-9b1e7ee4bb31.jpg)

**Comment by boy0001** [comment]
Insufficient info

**Comment by random1167** [comment]
updated to PlotSquared-Bukkit-3.4.1-5b103d4.jar and the roads seem to be off set
![y6r228t3](https://cloud.githubusercontent.com/assets/13611085/16108701/1acfa51c-33e8-11e6-956f-bede773c60a8.jpg)

**Comment by boy0001** [comment]
According to your other issue #1185 you updated then reverted without restoring the old configuration. 

The plots were reset to the default sizes because of this. PlotWorld configuration is now in the `worlds.yml` file. Please restore the correct values in that file and the plots will begin generating correctly.
