### ISSUE TITLE
Can we use lombok, plz? 

### ISSUE THREAD

**Issue by Sauilitired** [IntellectualSites/PlotSquared#1189]
Look at it: https://projectlombok.org/
Is amazing. For real. I've been using it for a couple of months, and it has honestly changed the way a code - for the better.

**Comment by MattBDev** [comment]
I prefer not to use it since using this only adds to the plugin size and writing the code out still gives you full power over what is going on in the code.

**Comment by boy0001** [comment]
Against
 - Most IDS's can already generate a class structure and such for you
 - Refactoring issues (e.g. refactoring fields may not change the accessors/mutators other classes are using)
 - No javadocs (since the methods aren't there you can't have javadocs)
 - Breaks navigation/search (e.g. find usages)
 - May break the CI servers
