### ISSUE TITLE
Bypass sware filters in PlotChat

### ISSUE THREAD

**Issue by Aeva-Network** [IntellectualSites/PlotSquared#1373]
When you have Plotchat activated and someone swared it buypasses all of the diffrent sware filters that i have found. Is there a way of getting these messages sent to the server for checking?

**Comment by chamunks** [comment]
You will likely need to follow the posting guidelines and include a /plot debugpaste as every chat handler tends to be different.

**Comment by boy0001** [comment]
The filter might/should have an option to set the priority it listens on. Set that to `LOWEST` if possible.

**Comment by oasis9** [comment]
This is still an issue, and I created a separate one with details on a suggestion on how to resolve it. Essentially P2 isn't detecting when a chat message is cancelled. I found it confusing that removing the ignoreCancelled=true didn't fix it, however. I'll look into that at some point; whether it defaults to true or is completely disregarded. Anyhow, even if `ignoreCancelled = true` is not removed from the annotation, an isCancelled check should be introduced. No point sending chat messages if they've been cancelled. If otherwise, I'm open for correction.

**Comment by boy0001** [comment]
@oasis9
That sounds like a different issue. More specifically it sounds like it is being cancelled at a higher priority, i.e. PlotSquared has already sent the message by that point.

**Comment by andris155** [comment]
LOWEST priority listener fix this. Thanks.

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
