### ISSUE TITLE
PlotSquared Schematic Roads

### ISSUE THREAD

**Issue by crysis992** [IntellectualSites/PlotSquared#1391]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**: http://hastebin.com/diyitalecu

**Description of the problem:**
I've created a road schematic with the /plot createroadschematic, tested it with debugroadregen, deleted then the creative world to let PlotSquared regenerate the whole world with the schematic. But at each crossroad there is 1 line of the road missing, which is filled with air + the road block (in my case 98).

And yes, I'm 100% sure I did not forget to build it :p Also tried to fill the hole, create a schematic again and let it regen all roads, same result. This row of blocks is missing every single time.

I've tested it with the latest Dev Build and the stable release from the spigot website, both have this error.

Screenshot:
![plot](https://cloud.githubusercontent.com/assets/5308174/19246040/96eec334-8f24-11e6-8a5c-95319dcbd75a.png)

Schematic that was saved:
https://crytec.net/downloads/schematics.zip

**How to replicate**:
I guess use the schematics and create a new world? 

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by MrPowerGamerBR** [comment]
Can confirm, this issue is also happening to me.

**Comment by PugaBear** [comment]
Also happening to me. 
![image](https://cloud.githubusercontent.com/assets/12417961/19505401/d9c29168-9587-11e6-90d7-0438d2f289ac.png)

**Comment by gabor6505** [comment]
Hi, I kind of figured out this issue and how to solve it in like 3 minutes, it's really easy. The issue is that the road width has the plot borders included in it (so if I set the road width to 7, 2 blocks will be under the 2 plot borders on the 2 sides of the road, and 5 blocks will be visible), so you just have to build the road schematic and save it 1 block farther, so the corner of the schematic just includes the 4 corner plot's corner block. Picture attached below about what I mean. I also figured out that it also transfers the plot borders with the road itself, so if I claimed the plot (and had the claimed plots' border be set to a different block) and then saved and generated the schematic, it would include the "claimed" borders as well. (and an empty sign). The author of the plugin should separate the actual road and the blocks under the plot borders. I hope that I was understandable, I am still a bit new to this issue reporting and helping stuff. (And  English is also not my main language)
![2016-10-20_18 16 21](https://cloud.githubusercontent.com/assets/12859334/19568336/76b86046-96f1-11e6-8655-36464a66df0f.png)

**Comment by boy0001** [comment]
Not a bug, you need to build the entire road on the north and northwest road to the plot. The border is included in the schematic.

**Comment by PugaBear** [comment]
@boy0001 this should be more clearly specified in the wiki. Generally people will just make the square around the path, and not include the two lines highlighted in the first picture. Most would consider that the next plot's path.

**Comment by boy0001** [comment]
@PugaBear 
Made some tweaks, feel free to edit the wiki:
https://github.com/IntellectualSites/PlotSquared/wiki/Installation#adding-road-schematics
