### ISSUE TITLE
lava/water bypasses road protection

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#1573]
picture says it all: https://i.gyazo.com/2befce924c889da81ad0f6f8d31ae957.jpg

**Comment by RedstoneFuture** [comment]
Right. **In Bukkit too.**


**Description of the problem:** 
The user can "spawn" water and lava over the plot.

**How to replicate:** 

1. Build this with a lava or water bucket in the dispenser.
![2018-04-27_20 32 48](https://user-images.githubusercontent.com/4140635/39379131-a4cd4bb8-4a5a-11e8-9a86-aade6b460fd8.png)

2. Activate this dispenser.
![2018-04-27_20 32 59](https://user-images.githubusercontent.com/4140635/39379171-c308cad0-4a5a-11e8-83c8-8298f352c1d9.png)
![2018-04-27_20 33 25](https://user-images.githubusercontent.com/4140635/39379172-c3298554-4a5a-11e8-8b43-af7fd61386bc.png)



**Checklist**:

- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/1950

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/1950

**Comment by BlightedBlue** [comment]
Status update on the issue? It seems high-priority.

**Comment by RedstoneFuture** [comment]
@BlightedBlue Is this still a problem? Than you can reopen this issue.

**Comment by AeSix** [comment]
I just tested this with 1.13.2 and P2 4.184. 
I tested with lava and tnt, with a similar setup as in the images. 

The lava and tnt are dispensed - however, the items are instantly removed when directed outside of the plot.  Both are dispensed if I face the dispenser into the plot.  This appears to be proper, expected behavior.  

***HOWEVER*** The original post was in regards to /Sponge/ - not Bukkit/Spigot/Paper. 
@PhanaticD - is this still an issue for Sponge?  If so, can you re-open it, or have someone with power re-open it?  If it's no longer an issue, state as such so @BlightedBlue (and the rest of us) will have a definitive answer.

**Comment by PhanaticD** [comment]
oh it was for nukkit judging from the texture, this is very old
