### ISSUE TITLE
Plotsquared bug

### ISSUE THREAD

**Issue by PedroCavalcanti0001** [IntellectualSites/PlotSquared#1703]
When a player leaves close to his plot the chunks unload ... But sometimes when he comes back they do not reload, making funnels, furnaces, potions support and so on ... How to solve? I am not the first one, that has this bug, in fact all the servers that I know that use plotsquared have this bug ...

I use spigot 1.8.8
Sorry for my English...

**Comment by zKingOfKill** [comment]
Funnels = hoppers 
Google Translator problem, Sorry.

**Comment by dordsor21** [comment]
So you have redstone.disable-unoccupied: true and/or redstone.disable-offline: true ?
(providing a /ps debugpaste will be helpful)

When a player therefore leaves their plot/server, the redstone/etc is turned off. But when they re-enter their plot, it's not all correctly turned back on. Would this be the bug?

**Comment by zKingOfKill** [comment]
This option is disabled, it's not just redstone related stuff, spawners stop working too, basically the chunk does not reload a few times and then buga, and only comes back when it reboots ... :(

**Comment by dordsor21** [comment]
It's possibly another installed plugin then. If you make a vanilla world (with multiverse; making sure it's not PlotSquared-managed) does this issue occur still? If possible, make a test server with all plugins but PlotSquared, and test.

**Comment by zKingOfKill** [comment]
I do not understand very well what you mean, excuse me, please, of course.

**Comment by zKingOfKill** [comment]
I do not understand very well what you mean, sorry to be clearer, please*

**Comment by shada124** [comment]
excuse me but I clised my server at three weeks ago...


بتاريخ 2017/08/22 10:10 م، كتب "zKingOfKill" <notifications@github.com>:

**Comment by dordsor21** [comment]
Run a test server without PlotSquared, but everything else. See if you keep having the problem.

**Comment by zKingOfKill** [comment]
I'll run, the problem is that the bug does not always happen ...

**Comment by Weber588** [comment]
I have a similar problem, and it has been around for a long time. There's another bug report with the same problem that was closed after a dev decided it was a config setting and didn't think to check if that was the actual cause...

The following permissions are DISABLED, and are not the cause:
redstone.disable-unoccupied
redstone.disable-offline

The issue in a little more detail: After ten to fourty minutes, hoppers will stop working, If you leave and return to the plot (unload then reload) the chunks, the time seems to reset. 

Hoppers work normally in non-Plot worlds that are virtually identical in every other way. In multiverse, the worlds have the same settings other than generation. 
The types of worlds we have:
Default generated super flat world: Hoppers are normal.
Default generated standard terrain world: Hoppers are normal.
Void world generated by CleanroomGenerator: Hoppers are normal.
Plot squared generated world: Hoppers break.

When the hoppers break, they act as though they are disabled with redstone.
I am using version 3.5.0-SNAPSHOT-95f8aaa

**Comment by alexmarkey** [comment]
We hare having this exact same bug on my server mc-central.net, and we are positive it is PlotSquared.
Like you said, we have many servers on our network, all of which are identical in many ways, however all tile entities seem to randomly freeze in only the plotworlds, no other worlds.

No clue what is triggering it, and having difficulty reproducing (seems to be extremely random as to when it happens)

**Comment by alexmarkey** [comment]
Okay I have just found the cause of this bug and how to reproduce it:

When a plot which has tile entities on it gets cleared, it makes all tile entities on the server in loaded chunks freeze:

How to reproduce:
https://www.youtube.com/watch?v=9D7inwYYXiw&feature=youtu.be

I have noticed in one of the latest dev builds, it claims to have fixed this issue, however after testing the latest dev build i can confirm that it is still there.  To reproduce use the following steps:

Claim 2 plots,
On plot 1 place a furnace smelting some ores
On plot 2 place some more random furnaces
Use /plot clear whilst standing on plot 2
The furnace on Plot 1 has now frozen, along with all other tile entities (hoppers, spawners, beacons, etc)

**Comment by zKingOfKill** [comment]
Helpppppp

**Comment by RedstoneFuture** [comment]
I have test it with https://www.youtube.com/watch?v=9D7inwYYXiw&feature=youtu.be by @alexmarkey on my test server, but I can replicate the problem. (I have a redstone server since a long time and I down't know this problem. Strange.) Can anyone test it with the current version of PlotSquared, please?

**Comment by AeSix** [comment]
Is this still an issue with newer builds of P2?
There's been a LOT of changes since August.  

Also @alexmarkey I would suggest that perhaps this is an issue with admin override abilities placing items on unclaimed plots.  Re-test with placing the furnaces on the plot before you claim them.  If the broder changing to redbrick slabs is you unclaiming the plot, then the issue is more of "why did the plot not get cleared"

These two issues (#1 from @PedroCavalcanti0001 and #2 from @alexmarkey)  should not be in the same github issue ticket.  

If the tile entity thing is still an issue with newer builds, please create a new issue.  Otherwise, update this ticket so it can be closed. 

Likewise with the original issue - if it's still an issue with a newer build, please generate a new debugpaste and update this ticket.  If it is no longer an issue, please update and close the ticket. 

Thank you! :)

**Comment by MattBDev** [comment]
This isn't a plotsquared bug. I believe it is a bug with spigot.
