### ISSUE TITLE
World Edit bug

### ISSUE THREAD

**Issue by TrexSo** [IntellectualSites/PlotSquared#1740]
When the players choose 2 own plots too far from each other with world edit. If they use the set command, the server freezes for 5-6 seconds.

**Comment by MAnoDew** [comment]
Please tell me more about this issue, this ain't enough to see what is causing this issue!

**Comment by TrexSo** [comment]
https://youtu.be/Sk3CPA0L_9w

**Comment by TrexSo** [comment]
I think this helps explain

**Comment by MAnoDew** [comment]
I personally recommend FastAsyncWorldEdit.
FAWE (FastAsyncWorldEdit) uses less memory than WorldEdit,
so the chance that your server crashes/lags, isn't there anymore.
It also stops queued tasks when your server is at low memory.
If you still want to use WorldEdit, ofcourse it is possible.
Use //fast and hf :smiley:
Important: You can't use //undo if //fast is enabled!
So make sure you do everything right in 1 time!

Hope I/this helped you!

**Comment by TrexSo** [comment]
I thought you were fixing your plugin.
To block a certain distance or something.
I would try to fix the source code myself.

**Comment by TrexSo** [comment]
If I had the source code, I would try to fix it myself.*

**Comment by Legoman99573** [comment]
Using worldedit by itself is just waiting for a crash to happen as worldedit commands are not threaded or asynced,  forcing the server to stop responding or take a long time to keep up.

**Comment by boy0001** [comment]
This is normal behavior because you have disabled WorldEdit restrictions or are using an unsupported version (update WorldEdit). 

As mentioned above, you should be using FAWE as well since normal WorldEdit is easily abused:
[boy0001/FastAsyncWorldedit/wiki/Download-Instructions:-Bukkit-Spigot](https://github.com/boy0001/FastAsyncWorldedit/wiki/Download-Instructions:-Bukkit-Spigot)

> If I had the source code, I would try to fix it myself.*

Both plugins are open source. You can access it by clicking the **code** tab above.
