### ISSUE TITLE
Pervasive Use of Deprecated Block IDs

### ISSUE THREAD

**Issue by md-5** [IntellectualSites/PlotSquared#1795]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 
Plugin makes use of integer block IDs where Material enum should be used.
Block IDs have been deprecated for > 4.5 years and are subject to removal:
https://www.spigotmc.org/threads/minecraft-1-13-what-to-expect.288714/

**How to replicate:** 

View the plugin source. Methods such as getTypeId and setTypeId should be replaced by getType and setType respectively.

**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by Sauilitired** [comment]
This was discussed a while back, and I'm not quite sure why we never got around to fix it. It should absolutely be a priority. 

It's just a matter of creating an implementation that works across all supported platforms. Unlike previous changes to the plugin I'd like to keep this structured. The code base is quite messy as is, and I don't want to make it worse. That's why [PlotBlock](https://github.com/IntellectualSites/PlotSquared/blob/master/Core/src/main/java/com/intellectualcrafters/plot/object/PlotBlock.java) and [PlotItemStack](https://github.com/IntellectualSites/PlotSquared/blob/master/Core/src/main/java/com/intellectualcrafters/plot/object/PlotItemStack.java) were introduced. (Although, even the PlotItemStack constructor that accepts a string ID relies on the numerical ID)

The easiest solution would be to just create a PlotMaterial enum. Although, in previous discussions it was also suggested that we'd use CSV files to allow for modded materials to be used as well. 

Feel free to disregard my ramblings 😆 I appreciate that this was brought up. I have been absent in the Minecraft world for quite some time, so I would have had no clue.

**Comment by Legoman99573** [comment]
I know i am late, and i am happy @md-5 is involved in this plugin. Plus i am hoping that this plugin can work out for 1.13, unlike WorldEdit where they decided they werent going to update the bukkit version, but will update the sponge version.

Lets hope PlotSquared doesnt head the same direction as they did.

**Comment by RedstoneFuture** [comment]
Can help the code of this program for the config conversion?

https://www.spigotmc.org/resources/id-converter.52099/

**Comment by Legoman99573** [comment]
@RedstoneFuture using minecraft:blockname should work as well but you would need to add "" and the block name inside those or yaml will crap itself.

**Comment by RedstoneFuture** [comment]
@Legoman99573 Yes, i know. Maybe it can help for the internal config-conversion-part in plotsquared. The program-code is open source. And Phoenix is a good developer.

**Comment by NinoM4ster** [comment]
Sorry to bump this, but I really need a solution.

I'm on 1.13.2 and I need to allow players to use a **dark_oak_button** (through the _use_ flag) but when it was added to the game the numeric IDs were already deprecated, so as far as I know, it has no id.

I tried using 143 (the common wooden button), **dark_oak_button**, **minecraft:dark_oak_button** and even **"minecraft:dark_oak_button"** (with quotes) but nothing appears to work.

Thank you in advance!
