### ISSUE TITLE
Economy

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquared#18]
Renting plots for an amount of time
Renting helper/trusted status of a plot
Selling helper/trusted status for a plot
Plot tax

**Comment by EvilOlaf** [comment]
> Selling plots (to other players)
+1

**Comment by boy0001** [comment]
Added (partially)

**Comment by EvilOlaf** [comment]
As somewhen in IRC I think already suggested I would like to see to sell a plot directly to another player either for a fixed price in config or the player sets the price by himself.
To make this possible even the potential seller is offline he could set a "forsale" flag on this plot with the price as parameter (or not, see previous clause :P). Another player could use "plot buy" on it and if he has the needed funds the ownership will be transferred.
Maybe it is useful to clear any trusted/helper/denied users while transferring the ownership. Another solution might be to ask the owner to removed any of these in order to be able to set the plot for sale.

**Comment by boy0001** [comment]
`E.g Player has plots.plot.1 permission > goes to a plot > claims that plot without paying anything > wants to claim another plot > types /buy plot for a specified amout of money > and so on`

**Comment by oDeathwingo** [comment]
If we can sell combined plots;
Also a permission to claim/buy max plot area(combined total area) ?
So everyone without a node like plots.claim.X only be able to buy plots as big as described in the config
claim:
  max-auto-area: 4
else with that node people can buy/claim bigger plots ?

**Comment by oDeathwingo** [comment]
or seperate the claim with buy and 2 default values with 2 different permissions ?

**Comment by arkobat** [comment]
Is /plot rent something we will see one day?
It would be cool to rent plots out near spawn, to ensure only active players can have them?
I would suggest a pr world fixed price in the config, or an option to define a price when setting the plot for rent.

Permissions:
It could be plots.rent.<ammount>, this is to separate them from normal plots.
If this is not a wanted behavior, it could also just be the normal permission.

Extend rent:
It would be awesome if you could have a max rent days set in config.yml, and players would need to keep logging in to extend rent.
This could either be done with a command or making players click the plot sign, to extend with 1 day.

Just some thoughts I had, as I can't seem to find a way to set plot for rent :)
