### ISSUE TITLE
Redstone Dispensers and or droppers not dropping items 

### ISSUE THREAD

**Issue by TauCubed** [IntellectualSites/PlotSquared#1844]
# Bug report template 
**Debug paste link: https://hastebin.com/ihegasuviy

**Description of the problem:** 

Droppers/Dispensers will NOT drop items, Dispensers will still dispense things such as shulkerbox_blocks and fireworks and spawn_eggs, they will not dispense/drop items.

**How to replicate:** 

1) Place a Dispenser and or dropper, add one or more items that will NOT cause the dispenser to "use" them (So, Not a flint and steel, bow, shulker box, mob egg etc), Or use a dropper. 
2) Power the dropper / dispenser.

Note: This issue instantly disappears when i unload the plotsquared plugin.

**Checklist**:

- [X] I included a `/plot debugpaste` link (Yes)
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue) (None that i can see)
- [X] I made sure I am using an up-to-date version of PlotSquared (Yes, just updated and re-checked while making this)
- [X] I Made sure the bug/error is not caused by any other plugin (I unloaded the PS plugin and it fixed it)

**Comment by alexmarkey** [comment]
Also experiencing this issue, any lead on it yet?

**Comment by joeymaeuslp** [comment]
i have the same problem shit plugin

**Comment by Opachl** [comment]
Please check this again look at #1775
i tested it just now it works so wich item did you try to place/dispense

please be clear if the issue is the dispenser or dropper :) its not the same

**Comment by alexmarkey** [comment]
The issue is with both Droppers and Dispensers.
The Item I have inside both of them is 64 dirt

https://gyazo.com/805a7246569720c4949257eb5936b171

Vanilla Minecraft would spit out an item drop.

I tested with Water buckets inside the dispenser, and they work fine like the author of this bug report stated.

**Comment by Opachl** [comment]
okay i had time to look i dont know why but my fix was reverted so the issue is back again.

See changeset https://github.com/IntellectualSites/PlotSquared/commit/bc8b2af164533ac982b0a07731e3c752fa958064 scroll down to the file changes for this class
Bukkit/src/main/java/com/plotsquared/bukkit/listeners/PlayerEvents.java

**Comment by WilliamEstrela** [comment]
I have the same problem

**Comment by xion87** [comment]
same problem anyone can care?
