### ISSUE TITLE
minecarts at the break road position

### ISSUE THREAD

**Issue by ScuroK** [IntellectualSites/PlotSquared#1890]
Im using the latest official build of plotsquared.
On merged plots items will disappear from chest-minecarts when the minecart drives to the location where the path used to be (before merging)

**How to replicate:** 
<!--- If you can reproduce the issue please tell us as detailed as possible step by step how to do that --
1. merge multiple plots
2. build a rail along this plot.
3. put a chest minecart with items on it. 
4. let it drive along the whole plot.

when the chest minecraft reaches the location where the street used to be, it will lose its items.

maybe i should mention that i use the config option to kill vehicles on roads.

**Comment by RedstoneFuture** [comment]
Right. I start the chest minecraft and at the middle (break road position) the minecart is hidt(!). It's crasy, because at the end of my rail line the minecraft is back. ;D


![2018-04-27_23 58 15](https://user-images.githubusercontent.com/4140635/39386897-f908e1b2-4a76-11e8-83ae-701250795bfd.png)
![2018-04-27_23 58 17](https://user-images.githubusercontent.com/4140635/39386898-f926efcc-4a76-11e8-8d78-ac1f2c629442.png)

**Comment by ScuroK** [comment]
its probably because of the "remove road vehicles" option.

**Comment by RedstoneFuture** [comment]
Have you the same bug? Or lose you still only the item?

**Comment by ScuroK** [comment]
AFAIK it just removes the item from the cart. i still belliefe it is related

**Comment by RedstoneFuture** [comment]
@ScuroK My writing graphic-bug was from LabyMod. ^^ And the problem with the inventar, I can't replicate too.

**Comment by RedstoneFuture** [comment]
@ScuroK Would like to test it without big seoncd-party plugins? I think it's not the problem of plotsquared.

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
