### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquared#19]
I think you (Citymonstret) mentioned that brandon was going to do this.
@brandonrelph

**Comment by Foorack** [comment]
@Sauilitired Any progress on this or can I work on it and make a pull request?

**Comment by Foorack** [comment]
@Sauilitired Why was this closed?

**Comment by Sauilitired** [comment]
All issues labelled with enhancement have been closed for now, as we are attempting to migrate suggestions to https://git.io/fN5B4 to properly organize suggestions. This is a well needed enhancement, however.

**Comment by Foorack** [comment]
@Sauilitired Why are those issues moved to a seperate repository? It will only make it more difficult to find.

**Comment by Sauilitired** [comment]
Because, whilst the issue tracker has been neglected for years, it would be nice to get it integrated into a proper workflow. Suggestions really doesn't fit into that workflow. This will be even more important with the coming merge with the breaking branch. 

Now, it might not be optimal as the current issues will then be harder to track down, sure. However, most of them haven't had any activity in years, and some of them are implemented already. If something is important enough to resurrect, then it could easily be moved to the new issue tracker, where it is far more likely to be seen.
