### ISSUE TITLE
WorldEdit Restrict Problem

### ISSUE THREAD

**Issue by MatinDark** [IntellectualSites/PlotSquared#1911]
i found bug about fastasyncworldedit and worldedit restrict on plotsquared if you trust someone and he do  //set lava after you untrust him he can go to his own plot and do //redo and that lava back again and again on that plot or he can use //undo too

**Comment by RedstoneFuture** [comment]
Right.

**Replication:**

1. UserA: /p trust <UserB>

2. UserB in the plot select a region and use e.g. "//set lava"

3. UserA: /p remove <UserB>

4. UserA can still use //undo & //redo

**Comment by RedstoneFuture** [comment]
And maybe the same permission-update-problem:

1. UserA: /p add <UserB>

2. UserB in the plot select a region and use e.g. "//set lava"

3. UserA left the game

4. UserB can can't select a new region in this plot, because he only added. But (!) he can still use worldedit-commands for the selected region, like "//set water".

**Comment by AeSix** [comment]
This seems like a duplicate issue of https://github.com/IntellectualSites/PlotSquared/issues/1473
