### ISSUE TITLE
Plot expiry problem

### ISSUE THREAD

**Issue by SouthCraft** [IntellectualSites/PlotSquared#1923]
Hello, i don´t know how i can set plot expiry to work correctly. I have set plot expiry set to true, and auto-clear task like this. I need to tasks:
1. For player activity - After 93 days any plot will be deleted of player.
2. Empty, or plots with 1-2 blocks changed delete after 1 day.
I have this config correctly setted? I have MySQLPlayerDataBridge and EssentialsMySQL. Is it problem for expiry? 

Config for auto-clear: https://pastebin.com/kyWTt6ft
Full config: https://pastebin.com/j1UUvaKh

**Comment by SrLeojaco** [comment]
I also tried this system so many times but i never get it working. I finally give up.

**Comment by SouthCraft** [comment]
Uh, and any solution for this? I need this feature, plot world will be soon full of unused plots :( And world will be have unnecessary space.

**Comment by AeSix** [comment]
This has been working for me since 1.11.
Ensure plot-expiry is true, and that your auto clear task has sane settings, including ensuring the name of the plot world for it to monitor.

If the owner comes online on the server (not the world or the plot), the count resets. 
I believe this also applies to trusted members as well. 

There is also a flag to prevent the automatic deletion of plots. 

If any of you are still having this issue, please reply to the ticket with a /plot debugpaste
Ensure you are using a new build.

**Comment by AeSix** [comment]
Closing as resolved due to working for me since 1.11 and still in 1.13.2
If anyone affected by this is still having an issue after updating and ensuring configuration, permissions and flags are properly set, please update and reopen.
