### ISSUE TITLE
problem to execute fixBorders.js script

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#1955]
**Description of the problem:** 

> script: https://github.com/IntellectualSites/PlotSquared/wiki/Fix-plot-borders

After the console command "`plot debugexec runasync fixBorders.js`" (with or without a id and a world) I get this warning: https://hastebin.com/vumomefota.php

Debugpast: https://hastebin.com/konexayobu

**How to replicate:** 

1. Download the script and put it in the script-file of P²
2. use "`plot debugexec runasync fixBorders.js`"

**Checklist**:
- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
@RedstoneFuture is this still an issue?
Were you able to fix the script? (Make a PR if you were?)

Obviously this is an ooold issue, and may have incidentally or purposefully been fixed by now. 

If it's still an issue with newer builds, a new debugpaste *might* be helpful, and a new warning/error paste would be great too, as the hastebins for both have expired.  Though the error may be included in the console log as part of debugpaste now.

**Comment by AeSix** [comment]
I believe this has been fixed, as I was able to fix borders in my plot world. Closing. Reopen if it's still an issue.
