### ISSUE TITLE
I can not use /p copy and /p move

### ISSUE THREAD

**Issue by Marvin10911** [IntellectualSites/PlotSquared#2001]
Hello,
when i try to type /p copy and /p move it comes Thats not a valid plot id ?

I dont use the same numer on these commands

Can anyone help me.

**Comment by RedstoneFuture** [comment]
go to a plot and write '/p move <second plot-id>'

**Comment by Marvin10911** [comment]
Yeah but when I write /p move than it say /p move plotid and when I write the plot Id in the commands it say That’s not a valid plot Id ??

**Comment by RedstoneFuture** [comment]
Move:

1. Go  to you plot with your build (e.g. plot ID "1;-2")
2. use `/p move <free plot ID e.g. "2;-2">`

Copy:

1. Go  to you plot with your build (e.g. plot ID "1;-2")
2. use `/p copy <free plot ID e.g. "2;-2">`

**Comment by RedstoneFuture** [comment]
Still a issue?

**Comment by AnimeDrache** [comment]
I tried this myself now. it "works" but not for move. If you move, then the same object spawn on the new empty plot but the empty plot is claimed now WITHOUT THE CLAIMED BORDER. the old plot keeps having the "claimed" border plus the object on it but its NOT claimed anymore.

**Comment by AeSix** [comment]
@AnimeDrache IF this is not regarding PlotSquare 4.40+ on Spigot/Paper 1.14.4, then please update and re-test. 
If this /is/ PS 4.40 on 1.14.4, please include a debugpaste.

Otherwise, the ticket will remain closed and no work will be done.  Only Spigot and Paper 1.14.4 servers are being supported with PlotSquare 4.40 and newer.  No other platforms or versions are being maintained currently.

**Comment by AnimeDrache** [comment]
Yes I do use **1.14.4** and **PlotSquared 4.400**

Here the debug: **https://athion.net/ISPaster/paste/view/31dc4fec31854ea4bfafec4d7b62bc4b**

**Comment by AeSix** [comment]
Why must people insist on using invalid block data?
Why are you appending ":100" to several blocks?  I see a lot of people doing this, but there is no reason to that I know of.  Please explain it to me. 

This alone may be causing your issue with not being able to copy and move, because the plugin don't know how to handle a block with a fake data. 

maybe @MattBDev can confirm or correct that?

**Comment by AnimeDrache** [comment]
Cause people are not always as deep inside the element as you are. Cause I have no clue at all what you are talking about. You have some knowledge that I don't have. I am like the most people, I put the plugin in, do some configs and it works. If this block error is causing any trouble, then its just for this case, cause otherwise everything works fine. If you could explain me what you mean, I am ready to fix it and to learn from the knowledge that you have.

**Comment by N0tMyFaultOG** [comment]
@AeSix 
> Why are you appending ":100" to several blocks? I see a lot of people doing this, but there is no reason to that I know of. Please explain it to me.

The `:<value>` is the percentage amount of blocks P2's generator will use to place blocks. So if it's set to 100 (which is actually redundant) it means that people did not read the wiki and just put some values in and expect it being working. So `50%stone,30%grass_block,20%sandstone` will use 50% of stone, 30% of grass_block and 20% of sandstone for example. But just submitting `:100` as 100% will not work.

**Comment by AnimeDrache** [comment]
I am still trying to figure out where to find this value and what to set it. Cause I dont want P2 to generate anything anywhere, I have my road which works fine and the plots are fine as well (first line grass, everything below is stone including the wall till bedrock)

**Comment by AeSix** [comment]
You know, had I seen something with 2 or more blocks, it would have hit me.  I recall reading that now.  Thank you NMF!

**Comment by AnimeDrache** [comment]
Okay so I should search for ":<value>" on the P2 wiki now?

**Comment by Sauilitired** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/BlockBucket

**Comment by AnimeDrache** [comment]
@Sauilitired Thank you for answering. I did read this website several times now and have to say that I still have no clue whats going on.

Guys I really dont want to bother anyone and I can imagine that you have much more knowledge about these things then me, but please understand me, I am just trying help (cause I can deal with the copy functionallity only). I thought it would be support for you if I add the issue here but its not like I need it to be fixed.

If you see its my fault cause I did something wrong, then I am really sorry for bothering or stealing any second of time but its not like I did it on purpose. You cant blame a child for not knowing how to cook if he doesnt have the skills for it. Just imagine me as the little boy who is willing to learn and not to bother his family.

However, I did read the website several times now plus the linked websites inside this post and I have still no clue what its talking about. Some kind of patterns okay but I dont use patters (I guess?) and there is also no information anywhere how to configure these patters / block buckets. Its just like an info link about block buckets in general but I cant see or find any information how to use them somewhere. I thought sometimes "maybe I need that to disable blocks on plots? Like disallowing more then 10 chests per plot?"

All that I can imagine is that you guys do maybe talk about this single line inside my "worlds.yml":

`      filling: stone:100`

If its so, please just tell me that this is what u were talking about the entire time. Cause otherwise there is no hint on any post, answer or website (or even better: an EXAMPLE) of where to configure or use any block buckets.

If its what I pasted, a simple: "remove the :100 in your world.yml" would have be the easiest way to help me. But even if, I would need further instructions. Do you want me to remove the :100 from the worlds.yml, reload, reboot and try the move command again before doing another debugpost or am I still missunderstanding?

Again, I am very sorry if this is causin trouble, I saw your discord often and how anoying people can be sometimes, but in this case, I am just not understanding correctly and thats something I need your tolerance for. Its not like I am to lazy to read or understand, I just simple never ever needed any block bucket feature and my plugin does work. But if you guys see an error and how to remove it, I would really, really appreciate your support.

**Comment by AeSix** [comment]
The support tickets are here for people to receive support.  Don't feel bad. 

My misunderstanding of what I thought were data values may have mucked up the support. I apologize for that. 

Stop your server,  delete fawe-dummy.jar  and install FAWE from https://intellectualsites.github.io/download/fawe.html
(it may re-create the dummy jar)

I'm waiting for clarification if the FAWE for 1.14.4 (unstable) is the suggested version for Spigot 1.14.4.  In the mean time, try it, and if it don't work, try the 1.13.2 version (it may work, again, waiting for someone to tell me)  Perhaps NotMyFault will see this and reply? :D

Also, I'm not sure if the "move" function of PlotSquared is working properly at all.  

Good luck, test subject!

**Comment by AnimeDrache** [comment]
Okay thanks for the answer @AeSix =).

I just wonder why I do have to use FAWE now to be able to fix the copy / move functionality correctly. I never ever used FAWE before =P. I just wonder what the *invalid block data* error was that you noticed before. I must have done any wrong setup somewhere. Can you tell me where I did it and what I have to remove to get rid off that error? <3
