### ISSUE TITLE
Getting more plots than allowed

### ISSUE THREAD

**Issue by SrLeojaco** [IntellectualSites/PlotSquared#2002]
Old post (2017): https://github.com/IntellectualSites/PlotSquared/issues/1781

I get an easy way to do this...
https://youtu.be/fKDJQU2fTg8

I will add a command-delay to prevent it on my server, but that is not a good solution and must be fixed.

PS: Despite i opened the issue with another version, before trying this, i tested on
PlotSquared-Bukkit-18.06.23-79e1ea9-2017

PS2: I tried on 3 different servers and it works

**Comment by xion87** [comment]
I confirm the issue is that why i got random people with more plots than allowed

**Comment by AeSix** [comment]
I am unable to duplicate this issue using 1.13.2 and P2 4.184

If either of you, @xion87 or @SrLeojaco are still having this issue, can you make sure you're using newer builds of P2, and that no other plugins (like your chat plugins) are not causing the issue?  

Update the ticket with a new /plot debugpaste if you are still having the issue.  Otherwise, update and let us know that you're not having the issue so the ticket can be closed.  Thank you :)

**Comment by SrLeojaco** [comment]
At the moment i'm not able to test it, but as soon as i can i will try

**Comment by xion87** [comment]
Bug still present
the guy just used p reset and p auto and at next restart they have 3 plots

**Comment by AeSix** [comment]
lacking information, not responding with information as asked. 
Video shows a non-repeatable exploit, possibly due to some other plugin or insufficient server/network resources available to the server. 

Issue has not been able to be duplicated elsewhere with a properly installed server and plugins.

**Comment by SrLeojaco** [comment]
Sorry for delay! I have been testing now on local and i can't reproduce the issue so it may be fixed. I'll upload to online server the lastest plotsquared build and i'll see it it reproduces.
