### ISSUE TITLE
UUID Converter

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [IntellectualSites/PlotSquared#2004]
When I do the conversion to online it kicks me and allows me back when joining. It turned the UUIDs into the online ones. But if I reboot me server after the conversion it simply turn the UUIDs back into offline mode. 

Why I'm reporting this is because if you make a plugin with the API it returns different values which is just impossible to code with. 

Is there a reason to why (after converting to online) it just converts back to offline after a reboot...

Running a server on bungee which is portforwarded and the server is in offline mode. It seems to look at my offline mode and not at my bungee, shouldn't it be online due to that?

**Comment by FadeCloudINC** [comment]
Having the same issue

**Comment by AeSix** [comment]
Make sure you clear (delete) your usercache.json so that the old UUIDs aren't being used again. 
You'll want to do this after conversion, but before anyone logs on.  Preferably with the server off. 

If running Spigot/Paper on Bungee:
Bungee online mode true, WITH IP forwarding to true
spigot online mode false AND to use bungee
plugins should then be set to be online mode. 

However, @LucKYsHoTSzZz  - did you find the solution? As the issue opener, you can close the ticket.
