### ISSUE TITLE
People with superpickaxe can destroy plots with p flag use 0/air

### ISSUE THREAD

**Issue by xion87** [IntellectualSites/PlotSquared#2048]
Debug paste link:
https://hastebin.com/eyilapacug

Description of the problem:
plots with flag use 0 can be destroyed by player with superpickaxe

How to replicate:
- have a plot with /p flag set use 0
- player with superpickaxe permission and fawe.plotsquared enter and press // and then he can break one block, doing // again you can break another one

Checklist:

  [x] included a /plot debugpaste link
  [x] made sure there are no duplicates of this report (Use Search)
  [x] made sure I am using an up-to-date version of PlotSquared
  [x] Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Can confirm the second message. If you have a plot with `/plot f set use 0` players are able to place boats and armorstands in off hand without being added or trusted to the plot. Tested on latest PlotSquared build.

**Comment by MattBDev** [comment]
@Xion87 still an issue?

**Comment by AeSix** [comment]
I'm unable to replicate this behavior in testing. 
Closing ticket due to no response from original poster.  

@xion87 if this is still an issue, report back, with better details and more information.
I tested with 4.305 on 1.13.2 and cannot replicate.  As your environment information is not available (paste is dead), I cannot test exactly as you were experiencing the issue.
