### ISSUE TITLE
Swap command moves wrong plots when swapping merged plots

### ISSUE THREAD

**Issue by ghost** [IntellectualSites/PlotSquared#2077]
# Bug report template 

**Debug paste link:** 

https://hastebin.com/zuriyaraxa

**Description of the problem:** 

If you do not stand in the north-western corner of a merged plot when using **/plots swap** it will move the wrong plots.

**How to replicate:** 
Merge 4 plots into a square and then merge another 4 plots to make another square of the same size. Attempt to swap these two by standing in a corner other than the north-western corner of one of the plots and doing **/plots swap <ID of plot you are not standing in>**.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Teriuihi** [comment]
Do /plot swap while standing in the red plot. The command references the orange plots coordinate. The red plot is the orange plot after the command. The grey plots are claimed plots that get nothing pasted on them. The pink plots are plots the get something pasted on them. Only one square (2x2) is claimed 3 plots get pasted outside claimed plots instead of being cut off.
![plot swap](https://user-images.githubusercontent.com/38841986/44465325-8591fe00-a61d-11e8-9661-1e1c5efd759b.png)

**Comment by AeSix** [comment]
Matt did some work with plot move and swap recently, to fix an issue for 1.13 - I *think* he may have did the same for 1.12.  Can you try using a newer build for 1.12 and see if the issue remains? 

If the issue remains, can you give us an updated /plot debugpaste please
If the issue has been resolved, let us know and close the ticket?  Thank you! :)

**Comment by MattBDev** [comment]
i haven't touched 1.12 swapping. this is the first time i saw this issue.

**Comment by Sauilitired** [comment]
Plot swapping of merged plots is not supported.
