### ISSUE TITLE
Worlds with non-default generator settings fail to properly convert some block data from 1.12 to 1.13

### ISSUE THREAD

**Issue by zombachu** [IntellectualSites/PlotSquared#2082]
# Bug report template 

**Debug paste link:** 

https://hastebin.com/homagidini

**Description of the problem:** 
When a plot world with non-default settings (tested in my case with a world with the floor block set to 159:11) is converted to 1.13(.1), seemingly all extra block data is reset. Directional blocks are set to their default direction, sign text is cleared, inventories are reset, skulls lose their owners, etc.

This behavior is not seen with non-PlotSquared worlds or plot worlds using the default settings (all data seems to be converted properly in these cases).

**How to replicate:** 

1. In 1.12, create a plot world with the floor set to 159:11, for example
2. Place some blocks to test such as ![2018-08-28_03 27 20](https://user-images.githubusercontent.com/7826590/44726693-06b12100-aa74-11e8-9216-7f8feb7698c7.png)
3. Stop the server, upgrade it to 1.13(.1), and start it with the `--forceUpgrade` flag appended
4. Any blocks with extra data should exhibit the previously-described behavior. In the case of the example test, 
![2018-08-28_03 27 25](https://user-images.githubusercontent.com/7826590/44726845-57c11500-aa74-11e8-8895-baf5a2fb2c4b.png)

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by eightbitx** [comment]
I also have this issue. During conversion for my 1.12.2 world in 1.13 I saw wool and wood lose it's color. Converting the world without PlotSquared install works fine, and generating a new world with PlotSquared works fine. But, when i try to convert the world with PlotSquared install, this happens.

https://imgur.com/c0jXa59
https://imgur.com/KITdPtK

**Comment by AeSix** [comment]
@MattBDev I did NOT have this issue when converting 1.12.2 to 1.13.2.  I replaced FAWE with WorldEdit 7 beta 4, and updated PlotSquared to v4 build 115 before the conversion. 

@eightbitx or @zombachu If this is still an issue for you, please provide a new /plot debugpaste and update the ticket.  Otherwise, update or close the ticket so the Devs don't have to worry about it any longer.

Thank you! :)

**Comment by eightbitx** [comment]
@AeSix Your message humors me. I'm not sure whether it's that this is the first time I've been asked to mark an issue as resolved for the developer rather than the developer doing it themselves, or whether it's that you think I'm still trying to convert my worlds to 1.13.x six months later. No, I gave up on 1.13 PlotSquared a long time ago.

**Comment by AeSix** [comment]
The state of PlotSquared is a LOT better than it was 6 months ago... even 2 months ago.  There's about to be a release build as well.  So, maybe it's time to try again? 

Additionally, I'm not a developer - just a person helping with issues where I can.  I don't have access to close tickets, and so I politely ask if the op would do so if applicable :)

If you do want to try again, I suggest using a copy of your server, start the server without any plugins, and with using the --forceUpgrade runtime option.  Let it take it's time to update the world.  Then add PlotSquared  4, and use WorldEdit 7 beta 5. FAWE and P2 aren't the best combination right now - but soon!  

I hope this helps!  Good luck with your ventures :)
