### ISSUE TITLE
ArmorStands can be pushed out of claim

### ISSUE THREAD

**Issue by EscolarProgramming** [IntellectualSites/PlotSquared#2089]
**Debug paste link:** 
Not possible because I get an 503 error for HasteBin. I'm running on PlotSquared-18.8.23-f5a981f-2037.

**Description of the problem:** 
Armorstands can be pushed to other claims using a redstone clock, a piston and a slimeblock. It doesn't happen every time, but in the most cases.

**How to replicate:** 
https://youtu.be/vAJHcN_rZp4
As you can see, the first on got pushed to the other claim, only the last one failed.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
I set up a test on my 1.12.2 creative server. 
The armor stand was indeed being pushed off the plot, however after a very short period of time, it was removed. 

>version
[12:56:36 INFO]: This server is running CraftBukkit version git-Spigot-642f6d2-fbe3046 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[12:56:36 INFO]: You are 415 version(s) behind
>version PlotSquared
[12:56:39 INFO]: PlotSquared version 18.11.15-0252cf7-2052

I however do have other protections in play:
I kill road entities with P2 (Probably whats killing the stand)
I also have redstoneclockdetector and redstoneclockpreventer
and WorldGuard (though, I believe WG is not enacting on this)

Likewise, I cannot place armor stands outside of my plot, including on the border wall. (I am Op and have all permissions/bypasses)

I suggest updating P2 and test again.

**Comment by Chazotu** [comment]
Just tested in latest version still works

**Comment by AeSix** [comment]
https://i.imgur.com/6A7dMvU.png
pistons are no longer able to push armor stands out of plots, whilst still able to push armor stands within plots. 

This is done on Spigot 1.13.2 using PlotSquared 4.305. 

HOWEVER
The machine in the video, which uses a sticky piston and slime block to throw a falling entity (armor stand) does still work to push the entity outside of the plot.  Upon entering the road, however, the armor stand is removed.  Presumably due to "kill road entities" in the config. 

This seems like something that does not need to be fixed.  The only thought on fixing this without mucking with base mechanics would be to have P2 disallow falling entities from exiting plots.  This is already done with the kill road entities config option. 

A feature request ticket should be opened to add "falling entities to be disallowed from exiting plot boundaries"  

On additional thought, this may be yet another symptom of https://github.com/IntellectualSites/PlotSquared/issues/2180  and https://github.com/IntellectualSites/PlotSquared/issues/2280

I am closing this ticket and opening a feature request for the above mentioned function.
In the mean time, use other methods to prevent players from piling up armor stands in the roads.
