### ISSUE TITLE
Updated on 1.12.2 and error in console

### ISSUE THREAD

**Issue by FrozenBeard** [IntellectualSites/PlotSquared#2114]
I updated my plotsquared on my 1.12.2 server and it gives me this error at boot.

https://pastebin.com/9R1hvxPG

**Comment by RedstoneFuture** [comment]
Do you install any addon for plotsquared? e.g. HoloPlots?

**Comment by FrozenBeard** [comment]
Yes I have holoplots

**Comment by RedstoneFuture** [comment]
Can you restart your server without Holoplots? It this a problem of Holoplots?

**Comment by AeSix** [comment]
Can you update to a newer build from
1.8.8-1.12.2:  https://ci.athion.net/view/Everything/job/PlotSquared/
Test with and without HoloPlots, as RedstoneFuture asked.  There has been a lot of updates since the original issue, and a similar issue was resolved with a newer build for me. 

If the issue persists, please update the ticket with a /plot debugpaste 
Otherwise, if the issue ceases with the newer builds, please close the ticket.

Thank you! :)

**Comment by MattBDev** [comment]
Since @FrozenBeard hasn't replied to the ticket since October. I am closing this issue. Feel free to reply if you believe it is still a problem.
