### ISSUE TITLE
How can I use /plot auto from a separate world?

### ISSUE THREAD

**Issue by danielgulic** [IntellectualSites/PlotSquared#2115]
Hi, I have a server with a world called `spawn` and a Plot World called `structure`. The `spawn` world has some huge buildings and holograms, and I'd like players to be able to use **`/plot auto`** from inside that world. Unfortunately I'm getting the "**You're not in a plot area**" error.
Is this possible, or do I *need* to have players run the command inside the Plot World?
P.S. My friend had it setup how I want, but he's unavailable for a while so I'm asking here. Surely it is possible?

**Comment by RedstoneFuture** [comment]
@danielgulic With the 1.13 supported version the plugin will you teleport with "/p auto" in a non-plotsquared world in a plotsquared-world. Latest test with "PlotSquared-Bukkit-18.08.12-4b8c434-2035.jar".

**Comment by RedstoneFuture** [comment]
@danielgulic But currently you can't define a specifically default plotworld, because plotsqaured checked all worlds and use at this situation the first found plotsquared-world. If you need a default world option in the settingy.yml aou can write a suggestion at here: https://github.com/IntellectualSites/PlotSquaredSuggestions

I hope this was helpful.
