### ISSUE TITLE
PS does not work with WE 7.x on 1.13.1

### ISSUE THREAD

**Issue by i9hdkill** [IntellectualSites/PlotSquared#2119]
**Debug paste link:** 

https://hastebin.com/movizuxizo
**Description of the problem:** 
When interact on plots or roads, PlotSquared checks if the hold item is the world edit wand item.
But in WE 7.x this field seems to be renamed, so PS fails wirth this error:
https://pastebin.com/xGv60paR

**How to replicate:** 

Install PS Build 635 on spigot 1.13.1 built on 04.10.18 with worldedit-bukkit-7.0.0_Build3874

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Drc-DEV** [comment]
This is really annoying

**Comment by x1p** [comment]
Same here
**Debug paste link:** 
https://hastebin.com/ixavocunob

**Description of the problem:** 
https://hastebin.com/etacovayuy.pl

**How to replicate:** 
I don't know what triggers it. The previous command performed by a player was /plot chat. The error keeps appearing >1000 times, then after 15 minutes, it stops.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)]
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by MegaNarwhal** [comment]
Any update on this?

**Comment by KurwyGithub** [comment]
Any update?
