### ISSUE TITLE
Unable to import template town

### ISSUE THREAD

**Issue by f0rb1d** [IntellectualSites/PlotSquared#2178]
# Bug report template 
**Debug paste link:** 
 https://hastebin.com/kumocahafa

**Description of the problem:** 
Sponge server failed generating worlds from template Town.

**How to replicate:** 
/p2 template import <worldname> town
Also, I am unable to import bridge and town templates (I haven't tested skyblock yet) in Sponge 8.0.0.

**Checklist**:
- [√] I included a `/plot debugpaste` link
- [√] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [√] I made sure I am using an up-to-date version of PlotSquared
- [√] I Made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
Hi @f0rb1d  - 8 and a half months later, and Sponge 8 is still in beta.  If this is an issue with the current stable version of Sponge, please open a new ticket with all information in the issue template. 

Closing ticket due to the issue being present on a beta release of Sponge, the same beta which has seemingly not been worked on in a year, according to spongepowered site. 

Again, if this is a legit issue with the latest build of PlotSquared designed to work on Sponge, and the latest build of STABLE Sponge 7, please open the ticket with ALL information as seen in the new issue template.  

Thanks :)
