### ISSUE TITLE
"/p flag set redstone false" stop not correctly all redstone mechanics

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#2202]
**Description of the problem:** 

(I don't need this flag, but it's implemented and I checked this. :D )

If I disable the "redstone" flag only the follow mechanics are blocked:

- light detector
- repeater
- comparator
- detector rail
- activator rail

All other redstone-block mechanics world sill as normal.

**How to replicate:** 

1.

`/p flag set redstone false`

2.

![2018-12-28_13 46 22](https://user-images.githubusercontent.com/4140635/50515788-01f28d00-0aa7-11e9-9559-a91e105c4486.png)

**Tested with:**
> spigot-1.13.2
> PlotSquared-Bukkit-4.18.12.28-6292bff-2124.jar

**Checklist**:

- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Chazotu** [comment]
In aktueller Version wieder vorhanden 

1. TNT läst sich von allen Redstone Sachen enzünden
2. Piston,Sticky-Piston,Dispenser,Dropper werden von direktem Redstone Signal (Fackel,Redstone Block gepowert)

**Comment by xWavePlayzx** [comment]
**Description of the problem:**
If I disable the "redstone" flag the following mechanics are **not** blocked if redstone block or a redstone torch is used:
dropper
dispenser
noteblock
(sticky)piston
fence gate
trapdoor (with block update)
lamp (if power source is placed before)
All other redstone-block mechanics are blocked successfully.
**How to replicate:**
1.
`/p flag set redstone false`
2.
![2020-03-16_01 54 15](https://user-images.githubusercontent.com/62224323/76714747-4197aa00-6729-11ea-9f6d-f66bc9882f5d.png)

**Tested with:**

> Paper-1.15.2
> PlotSquared-Bukkit-4.486.jar

**Checklist:**
 
- [x] I made sure there are no duplicates of this report (Use Search)

- [x] I made sure I am using an up-to-date version of PlotSquared

- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
@RedstoneFuture Why was this reopened?

**Comment by RedstoneFuture** [comment]
@MattBDev Because the post by xWavePlayzx (it's a  teammate by me)

**Comment by RedstoneFuture** [comment]
The most of redstone mechanics are blocked with this flag. Only block-updates are the problem at here. For example with a block-update a dispenser will drop her item. Or you activate a notepad with a redstone-block place event.

I down't know the usage and the concept of this flag: maybe this currently worked feature are good enought for the user there use this flag in her plot / at her server.

**Comment by RedstoneFuture** [comment]
@Sauilitired If you think the status after my last post are acceptable, than we can close it.

It's not perfect but I'm fine with this.

**Comment by RedstoneFuture** [comment]
![grafik](https://user-images.githubusercontent.com/4140635/118878062-7421d180-b8ef-11eb-8c18-740877ffd22e.png)

copy of https://issues.intellectualsites.com/issue/PS-116
