### ISSUE TITLE
Can't create custom schematic road

### ISSUE THREAD

**Issue by PinoyLifeCraft** [IntellectualSites/PlotSquared#2227]
**Debug Pastelink**

https://hastebin.com/oliqeliyut

Hello there guys?

I can't create my road schematic /plot createroadschematic no error found on console I am also using the latest pre- release PlotSquared-Bukkit-19.01.03-b288a2d-2044.jar when doin' /plot debugroadregen it pasted nothing (no error found on console).

It also do not create a schematic folder :disappointed:  Please help me?

**Comment by N0tMyFaultOG** [comment]
- Update your p2 version to the 1.13 supportive one: https://ci.athion.net/job/PlotSquared-Breaking/lastSuccessfulBuild/artifact/target/PlotSquared-Bukkit-4.88.jar

- Remove Fawe/Favs and use WorldEdit since P2 v4 depends on it http://builds.enginehub.org/job/worldedit/10826/download/worldedit-bukkit-7.0.0-SNAPSHOT-dist.jar

- Follow this guide properly https://github.com/IntellectualSites/PlotSquared/wiki/Installation#initial-setup, scroll down incase you are updating to 1.13, the wiki has a special paragraph for it.
