### ISSUE TITLE
Plotsquared api and lowercase uuid setting with ProtectionLib

### ISSUE THREAD

**Issue by xion87** [IntellectualSites/PlotSquared#2253]
# Bug report template 
**Debug paste link:**  https://incendo.org/paste/view/2f36de2c7d62443f8fa8e3d9665c707c

**Description of the problem:** 
The problem is the following, i am using plotsquared in offline mode with force-lowercase setting enabled. I use another plugin called Furniture and ProtectionLib (that support latest plotsquared api)
By using it and giving the player the correct permission, only the players with lowercase names are able to place forniture (instead the players with capitalized name are not able to place, you will trow only the furniture egg) 
We tested with the furniturelib author and we are able to replicate the issue in his test server, he say  he used the correct method for get uuid as you can see here: https://github.com/Ste3et/ProtectionLib/blob/master/src/de/Ste3et_C0st/ProtectionLib/main/plugins/fPlotSquared.java#L62

**How to replicate:** 
enable force-lowercase: true and user furniture/protectionlib, user with lowercase names will be able to use text, instead others will be not able

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
what version of p2?
what version of mc?
what server distro?
what perm system?

Yes, debugpaste is necessary. These questions would be answered.

And just because one dev says his poo smells like roses does not ,ean he don't lie. I've had issues, personally, with DiceFurniture.

 And finally, lowercase UUIDs are there to fix a specific issue, and if you're not affected by that issue, you should not be using it.

**Comment by xion87** [comment]
Updated the first post with debugpaste

I used lowercase setting because 4 years ago i don't have any protection to prevent user to login with different/incorect name cases, so the plotsquared dev suggested to enable  lowercase to prevent issue with plots because this, now i stopped to have issue of this type, but i can't revert the setting because i think i will lose all plots, we don't know 100% if is a plotsquared issue or protectionlib fault @Ste3et_C0st

**Comment by AeSix** [comment]
Make a backup. Full backup.  All files, configs, database. Everything. Stash that away.

Change the force lowercase to false.  Start your server.  Test. It should not remove any plots or plot-user associations. If I'm wrong, you'll want to restore from backups, because of any possible config/file/db corruption. 

Other than that, the force lowercase seems to be working properly.  Dice is not working against P2's API properly, otherwise it would be able to account for the force lowercase.  The dev is in his rights not to support this however. 

Additionally, you will want to restart your server and run a new debugpaste, so the start up section of your latest.log can be included, as it currently is not.

**Comment by Ste3et** [comment]
I want to fix it, but why plotsquared lowercase the uuid of a player and set it as plot owner uuid ?
this is my current code of my plugin protectionlib https://github.com/Ste3et/ProtectionLib/blob/master/src/de/Ste3et_C0st/ProtectionLib/main/plugins/fPlotSquared.java#L49

**Comment by xion87** [comment]
try to look here: https://github.com/IntellectualSites/PlotSquared/blob/master/Core/src/main/java/com/intellectualcrafters/plot/object/PlotPlayer.java

**Comment by Ste3et** [comment]
i have see it and i work currently on it.

**Comment by xion87** [comment]
Great! ping me when there is a dev build ready so i can test ;)

**Comment by Ste3et** [comment]
ok dev build is building and available soon at my download center https://dicecraft.de/furniture/download.php?plugin=ProtectionLib&build=DevBuild&version=Spigot%201.13.x

**Comment by Ste3et** [comment]
no problem sorry for the long delay after the report, but i have no time under the week to programm excessive on my plugins.

**Comment by AeSix** [comment]
So, can this be closed now, or is there still an issue?
