### ISSUE TITLE
Version Bugged 

### ISSUE THREAD

**Issue by Jeggur** [IntellectualSites/PlotSquared#2299]
# Bug report template 

**Debug paste link:** 
https://incendo.org/paste/view/0f067d343fd2438fb8f26f5ed2772fb5

**Description of the problem:** So I first downloaded the latest version of PlotSquared 1.12.2. When I first tried to create a world with mv, it said complete, but when I tried to teleport to it, it made me confirm because it was "unsafe". After that, it made my server crash and I had to completely remove the world and join back in. Afterward, any command related to the plugin did nothing. Literally nothing. I checked the console. Nothing. So I was told to get the February version instead. Luckily that fixed my problem. So the main issue is that the latest version is completely bugged and was the main source of my problem.

**How to replicate:** 
So just get mv and the latest version of 1.12.2 PlotSquared. That's basically it

**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
I requested this user to open this ticket.  I also told them to use the newer version again to try building the world fresh, to make sure the issue was persistent.  I don't see that they've done this.  

Additional testing would be to:
1) use the newer build to create a world:
 - use JUST p2 to create the world, not MV - if fails, is an issue with P2, else continue
 - use P2 with MV - if fails, probably an issue with that build of P2 and MV
2) Use a build from Feb to test:
 - if newer build created a world, load with older build to test creation success
 - if newer build failed to create a world, create a world with older build and update to newer build

I don't have the time right now to do this testing.  Perhaps @Jeggur would be kind enough to do so?

**Comment by MattBDev** [comment]
Since incendo is now offline and no other reports have been made regarding this issue, I will be closing it.
