### ISSUE TITLE
creative mode problem

### ISSUE THREAD

**Issue by soshimee** [IntellectualSites/PlotSquared#2354]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** 
PlotSquared-18.12.12-be48507-2053
**[REQUIRED] Spigot/Paper Version Number:** 
git-Spigot-e8ded36-acbc348
**[REQUIRED] Minecraft Version Number:** 
340
**Links to worlds.yml file and settings.yml file:** 

**[REQUIRED] Description of the problem:** 
Users on plot world switch to creative, but sometimes when they leave the world, they don't switch to survival mode.
**Any relevant console output or screenshots:**

**Plugins being used on the server:**
ColoredSigns, MYSlots, EasySetSpawn, BetterChairs, NametagEdit, ConsoleSpamFix, OreGenerator, SkinsRestorer, AutoRestart, AntiJoinBot, Ping, SimpleAPI, StaffPlus, Actionbar, CountryOnJoin, CratesPlus, dynmap, SeePlayerInventory, Skript, ColorfulCommands, EasyCarts, InGameConsole, Votifier, tpa, VotingPlugin, FastAsyncWorldEdit, Signsee, PermissionsEx, CS-CoreLib, Vault, CustomChatPrefix, FastAsyncVoxelSniper, VariableTriggers, GUIShop, ASkyBlock, ChestCommands, VoxelSniper, SignBoard, MyCommand, WorldEdit, Essentials, CrazyAuctions, WorldGuard, SimplePets, Citizens, Shopkeepers, ProtocolSupport, PlotSquared, MultiWorld, CitizensCMD, ViaVersion, ProtocolLib, GriefPrevention, AuthMe, TriggerReactor, LockettePro, Orebfuscator4, NoCollide

**How to replicate:** 

**Checklist**:

- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
try updating. Since you failed to actually give useful information regarding the version of Minecraft you're using (340 is not a version, perhaps it's a protocol version?)  I'm going to assume you're on 1.12.2. 
You can find legacy version builds (for Minecraft 1.18 through 1.12.2) here: http://ci.athion.net/job/PlotSquared-Legacy/

Please update, test and if the issue has been resolved, please close the ticket.   If the issue is not resolved, then it's more than likely a configuration issue and you should seek real-time assistance in the Discord.  If you choose to do so and your issue is resolved, please close the ticket.  

Thank you.

**Comment by dordsor21** [comment]
Seems that whatever plugin is supposed to turn players back to survival is the one that's buggy.
