### ISSUE TITLE
How do I create a OpenWorldGenerator with BiomeBundle Plotquared world?

### ISSUE THREAD

**Issue by FrozenBeard** [IntellectualSites/PlotSquared#2393]
I can create a Biombundle world with Multiverse, but what I cant figure out is how to make this world a plot world (Without roads)
I figured out 
/plot area create PirateCraft_bb1 type=1 terrain=3 gap=0
Creates a new world with no roads, but I cant tell it to use the OpenWorldGenerator generator.

**Comment by AeSix** [comment]
Closing due to a) a question which is answered on the wiki, b) not enough information provided - deleted the template, and c) Cannot find "OpenWorldGenerator" (best guess is Open Terrain Generator?) 

You should seek assistance from the community on Discord for questions.  https://discord.gg/ebreupz

**Comment by FrozenBeard** [comment]
Yeah open terrain generator not open world generator. 
What wiki? link me?
