### ISSUE TITLE
setComponent method broken / setComponent method type is ignored ?

### ISSUE THREAD

**Issue by UtechtDustin** [IntellectualSites/PlotSquared#2438]
Newest Spigot/PLotSquared(-API) Version will be used.

Why does the method setComponent dont work correct for me ?

If i use 
`currentPlot.setComponent("border", "dirt");`
or
`currentPlot.setComponent("outline", "dirt");`
or
`currentPlot.setComponent("wall", "dirt");`

The first call of setcomponent will be cached.. so the sond (different) will be ignored...
Why ?

---
Also it dont matter which type i use, the whole plot will get walls ;o
I only want the borders and/or the walls under the road height
It seems plotsquared will always use the all (https://github.com/IntellectualSites/PlotSquared/blob/095dccd30f07af2f58775393704bb5a77434640a/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/generator/ClassicPlotManager.java#L32) type

**Comment by MattBDev** [comment]
I'm not sure what your asking but this is a question that should be discussed on discord instead.

**Comment by UtechtDustin** [comment]
I already asked on discord, but no body answered..
The issue is that the method setComponent is not working correct.
If i use the method once with 'wall' as example it works, on the seond time with 'border' he will still use 'wall'.

Also often it seems he use 'all' instead of my option e.g. 'border', which means the whole plot has a wall.

**Comment by AeSix** [comment]
The discord guild is the best place to get assistance with issues regarding the api, custom add-ons, integrations, etc.  

Discord is a live chat environment.  Which means, it can either be completely dead if no one is on or paying attention,  it means that not everyone in the channel is going to know the answer to your questions, and it means that if you ask a question and it scrolls off the screen - no one will be looking for it to answer it.   You'll need to take some personal responsibility to ensure that you a) have the attention of people in the channel, b) are able to discuss the issue civilly, appropriately and with people who can actually help, and c) not act like a child and throw your hands up after 10 minutes of no one bothering to bow to your whims. 

Assuming you can do all three, it can still take quite some time for your issue to be resolved - if at all.  Some issues are simply incompatible with the way the plugin is designed to work. 

If you have valid proof that a portion of the plugins' code is wrong, create a new issue regarding that - not asking for help with your addon.  Or, better, since you're obviously a developer, present valid, legitimate, working code for which to replace the broken code.  Ensure it does not break expected behavior, and is not going to break other things.  AFAIK The team gladly accepts PRs from others.
