### ISSUE TITLE
worldedit bypass not working (Spigot) (IDK if its the plugin or not)

### ISSUE THREAD

**Issue by alexvermaning0** [IntellectualSites/PlotSquared#2441]
**[REQUIRED] PlotSquared Version Number:** PlotSquared-18.12.26-e3192f0-2060

**[REQUIRED] Spigot/Paper Version Number:** spigot 1.12.2-r.01-SNAPSHOT

**[REQUIRED] Minecraft Version Number: 1.13.2

**Links to worlds.yml file and settings.yml file:** 
i dont think its related in the 2 files i diden't change them

**[REQUIRED] Description of the problem:** 

the group has the permission
![image](https://user-images.githubusercontent.com/17603899/61870924-b50d5280-aedf-11e9-9c4e-a22e3b409f83.png)
and this is whats happening
![image](https://user-images.githubusercontent.com/17603899/61870977-dcfcb600-aedf-11e9-93fe-f84ac230b0b2.png)

i gave this perm pack on recomedation from fawe
![image](https://user-images.githubusercontent.com/17603899/61871057-159c8f80-aee0-11e9-845d-ecbbcc652fae.png)

**Plugins being used on the server:**
a lot of the plugins but i think its one of the 4 plugins

Worldguard
Ultra permissions
plotsquared
FastAsyncWorldedit

**How to replicate:** 
i don't think its easy to replicate i use an permission plugin thats premium.

**Checklist**:

- [] I included all information required in the sections above (check)
- [] I made sure there are no duplicates of this report [(Use Search)] (not found)
- [] I made sure I am using an up-to-date version of PlotSquared (IDK)
- [] I made sure the bug/error is not caused by any other plugin (idk if it is or not)

**Comment by AeSix** [comment]
~~~It would be best if you could verify that this issue is not caused by your permission management system by standing up a copy of the server using PEX or LuckPerms. 

Or asking the Ultra Perms authors if they have gotten similar reports, and/or can test, or if they would be willing to donate a copy to the project to ensure P2 is working correctly with it.  

BUT if Ultra Perms is using Vault, there shouldn't be an issue with P2 code, as Vault handles the permission calls.  So, if it is UP, it's all on their side.  

So, yeah, it'd just be best if you could test your specific setup using another permission plugin. ~~~

You say you're using 
```
[REQUIRED] PlotSquared Version Number: PlotSquared-18.12.26-e3192f0-2060

[REQUIRED] Spigot/Paper Version Number: spigot 1.12.2-r.01-SNAPSHOT

**[REQUIRED] Minecraft Version Number: 1.13.2
```

So, PlotSquared 18.* is for 1.12.2  PlotSquared 4.xxx is for 1.13.2-1.14.4
Make sure you're using the right version of P2 on your server.

**Comment by AeSix** [comment]
it's been 5 days with no response. closing ticket.

**Comment by alexvermaning0** [comment]
yea i forgot about this because i wasen't working on my server for a little while. but the server is 1.12.2 but i joined with minecraft 1.13.2
