### ISSUE TITLE
Unable to take damage from MOBs on unclaimed plots

### ISSUE THREAD

**Issue by Voxsolus** [IntellectualSites/PlotSquared#2451]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number: PlotSquared 4.298 

**[REQUIRED] Spigot/Paper Version Number:** 1.14.4

**[REQUIRED] Minecraft Version Number:**  1.14.4

**Links to worlds.yml file and settings.yml file:** 
world: https://pastebin.com/Zjwhpub3
setting: https://pastebin.com/TKx2FvKn

**[REQUIRED] Description of the problem:** 
Players are unable to take damage from mobs in unclaimed plots with no other plugin active on the server. if a flag is set manually on a plot you can then take damage but the world flag in the worlds.yml does not set the flag for unclaimed plots. Creepers are also unable to cause block damage. 

**Any relevant console output or screenshots:**

**Plugins being used on the server:**

**How to replicate:** 

Setup a server with just plot squared and worldedit and you can replicate this straight away by adding pve: true to world flags in  worlds.yml. go on your server survival mode you will not be able to take dmg

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
This is intentional

**Comment by Voxsolus** [comment]
Hi Matt,

Thanks for the fast response.

If this is intentional can there be an option to disable it so players can play normal survival on unclaimed plots?

It doesn't make logical sense to restrict this without an option to disable it in the setting.yml

**Comment by AeSix** [comment]
Actually, it does. 
Plots are protection areas.  This would affect other things, such as death chests, loot drops, etc. 
What happens if someone with a lot of high level gear dies on an empty plot, their loot put into a chest - annnnnd they can't access the chest because the way that plugin works.  Make it worse now, someone else claims the plot - and now the chest is in /their/ plot. 

Other plugins, other functions rely on plots to be claimed to function properly as well, and disable those functions when attempted to be used in unclaimed plots. 

PlotSquared works by giving players permissions to areas, in all that includes.

If you want accessible wild areas, I suggest re-doing the world with areas of plots using the hybrid model.

**Comment by Voxsolus** [comment]
Hi Thanks for the response.

The example you have given is very specific and implies that loot dropped goes in to a chest.

I have a survival server where you can build on all public land you can then buy plots once you have occurred enough money. 

any loots dropped on any plot is free to be picked up by who every?

If I set a world flag I would assume it would effect the whole world not just claimed plots? 

I've looked in to generating a hybrid plot as you mentioned but its not very documented on how to do this, does this require me programming the generator myself?  

Thanks for any help.

**Comment by AeSix** [comment]
Yes, thats *YOUR* setup.  Any plugin like PlotSquared shouldn't cater to niche use case scenarios, and should instead focus on normal use cases.  PlotSquared does allow for add-ons, so perhaps this is something you can yourself, or have someone create for you.

Hybrid plot worlds should not require anything other than PlotSquared to be used.  The documentation is a bit bad, and could be re-written / added to.  However, it's been a long time since I created a hybrid world and do not remember how, however I did follow the wiki.  

If you have specific questions regarding that, or need help, the Discord server has a lot of very helpful people, and should be your secondary source (after the wiki) for attaining this level of assistance.
