### ISSUE TITLE
Issue claiming plots for free!

### ISSUE THREAD

**Issue by AYNATANYA** [IntellectualSites/PlotSquared#2453]
**[REQUIRED] PlotSquared Version Number:** 
PlotSquared-4.305

**[REQUIRED] Spigot/Paper Version Number:** 
git-Spigot-9de398a-9c887d4 (MC: 1.14.4) 

**[REQUIRED] Minecraft Version Number:** 
1.14.4

**Links to worlds.yml file and settings.yml file:** 
https://athion.net/ISPaster/paste/view/5332124f7f644835b4d7b1b10b1c085d

**[REQUIRED] Description of the problem:** 
When people claim plots, it gives for free, i set True in economy, and if i do /plot reload it works, but if i restart the server dont work another time and i have to do /plot reload another time. 

**Any relevant console output or screenshots:**
All console when i start the server: https://pastebin.com/iLTMWSF7

**Plugins being used on the server:**
Quickshop, PlotSquared, WorldEdit, WorldGuard, Multiverse-Portals, Multiverse-Core, ClearLagg, Vault, SimpleJail, Ultimate_Economy, LuckPerms

**How to replicate:** 
- People claim a plot, take plot for free
- Config worlds.yml and i set it TRUE
- I do /plot reload
- It works, people claim a plot, it cost 100 money
- Restart server
- People claim a plot, take plot for free
- If i do /plot reload it works, but i have to do /plot reload ALL restarts to work

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
Reading Ultimate Economy, it looks like it may be an issue with them.  

It would be helpful if you could test your setup, with a complete copy, using another economy plugin, and without Ultimate Economy.  If you continue to have the issue when using another, update the ticket. 

Alternatively, you can seek assistance from the UE devs/community to see if others are having the issue. 

You may want to try using Vault 1.7.*1* as well, as a) I know it works, and b) I've had issues with .2 with other things.  

If none of these work, then you may want to set up a new server, with just P2, vault, CraftConomy3, and LP.  

Ultimately, economy works fine for me, and I believe this is not an issue with P2 - but I am not willing to straight up rule it out.   I also don't have time to set up a test server with UE.   Maybe someone else can replicate your results with UE, and confirm the issue lies there.

**Comment by AYNATANYA** [comment]
I tried before i post here with others Economy plugins, EconomyPlus, for example. And not work, i tried with vault 1.7.1 too.

**Comment by MattBDev** [comment]
After going through and testing I cannot reproduce this .
