### ISSUE TITLE
not permission of block-place because no permission for interaction

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#2483]
**[REQUIRED] PlotSquared Version Number:**
4.340

**[REQUIRED] Spigot/Paper Version Number:** 
Paper-Build #624

**[REQUIRED] Minecraft Version Number:** 
MC 1.13.2

**Links to worlds.yml file and settings.yml file:** 
-

**[REQUIRED] Description of the problem:** 
Permission destriction based strage situation:
1. Users can't place blocks If they don't have permissions to the use flag. Is that wanted?
2. Is `/p flag add all` or a `/p flag add *` valid  flag-definition? PS mean it's successful added, but he down't add all players.

**Any relevant console output or screenshots:**
-

**Plugins being used on the server:**
LuckPerms, PS, FAWE, Multiverse

**How to replicate:** 
- /p flag add use observer
- /p flag add all
- /p flag add *

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by mindw0rm** [comment]
>     1. Users can't place blocks If they don't have permissions to the use flag. Is that wanted?

I guess it is wanted, because the _use_ flag has nothing to do with block placement (it controls block usage, like doors, chests, etc.).

>     2. Is `/p flag add all` or a `/p flag add *` valid  flag-definition? PS mean it's successful added, but he down't add all players.

I looked into the [parse function](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Bukkit/src/main/java/com/github/intellectualsites/plotsquared/bukkit/util/BukkitLegacyMappings.java#L741) (see [here](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/flag/PlotBlockListFlag.java#L22) and [here](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/flag/Flags.java#L61)), and it seems to me, that "all" or "*" are not valid values. 
I think the main issue is that _use_ (and _place_ and _break_) is _not_ a list of players, but a list of blocks/materials.

**Comment by AeSix** [comment]
That is correct, use/place/break are blocks/items - NOT players.

**Comment by RedstoneFuture** [comment]
I must define "use" and "place" flag for the same block, If I will give the permission to place a block from a guest.


> I looked into the [parse function](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Bukkit/src/main/java/com/github/intellectualsites/plotsquared/bukkit/util/BukkitLegacyMappings.java#L741) (see [here](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/flag/PlotBlockListFlag.java#L22) and [here](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/flag/Flags.java#L61)), and it seems to me, that "all" or "*" are not valid values.

Then the messages from PS are wrong.

**Comment by mindw0rm** [comment]
> I must define "use" and "place" flag for the same block, If I will give the permission to place a block from a guest. This isn't useful.

Not really, you need "use" only for usage of the block, e.g. opening/closing a door, pulling a lever, looking into (and looting!) a chest, etc. 
For block placement, only "place" is required (but because of  #2524, the block that your guests click at while placing also needs to be in "place"). At least that's how it works for me. (*)

> > I looked into the [parse function](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Bukkit/src/main/java/com/github/intellectualsites/plotsquared/bukkit/util/BukkitLegacyMappings.java#L741) (see [here](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/flag/PlotBlockListFlag.java#L22) and [here](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/flag/Flags.java#L61)), and it seems to me, that "all" or "*" are not valid values.
> 
> Then the messages from PS are wrong.

I just tested it with my version (which is essentially the current github HEAD (from branch breaking)), and the error messages are as expected: (*)

>    /p flag add use observer

-> "flag added successfully" (no surprise, since observer is a block)

>    /p flag add all
>    /p flag add *

-> "flag couldn't be set" for both

[actual messages might slightly differ, the ones I've got are in German ;) ]

(*) Maybe you use an older version (the jenkins dev build is almost 20 commits behind HEAD, the release even more) and it got fixed since then?

**Comment by AeSix** [comment]
that's because there is no flag named "all" nor one named "*"

**Comment by mindw0rm** [comment]
Oops ...
Well, what I tested was `/flag add use all` and `/flag add use *` - I just copied the above from the op without realizing that they are wrong. 

`/p flag add all` and `/p flag add *` both tell me that it's not a valid flag.

**Comment by Sauilitired** [comment]
I suppose we should add `*` as a block wildcard.

**Comment by mindw0rm** [comment]
[Air](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/object/StringPlotBlock.java#L15) [is used](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/object/LegacyPlotBlock.java#L11) [for](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/object/PlotBlock.java#L21) [that](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/object/PlotBlock.java#L25), but it isn't checked everywhere; e.g. [here](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/util/EventUtil.java#L126) (*) it is, but [here](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Bukkit/src/main/java/com/github/intellectualsites/plotsquared/bukkit/listeners/PlayerEvents.java#L2387) it is not.

(*) here "use" is checked for break block (along with "break" directly afterwards).  This seems to be a bug in itself: breaking a block is not rejected if it is in the "use" flag. But since there is [another check](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Bukkit/src/main/java/com/github/intellectualsites/plotsquared/bukkit/listeners/PlayerEvents.java#L1018) (which also does not check for everything), I guess that can't result in wrong behaviour ...

**Comment by N0tMyFaultOG** [comment]
Having the place flag set lets the user place blocks fine.
