### ISSUE TITLE
Problem with /plot setowner command usage

### ISSUE THREAD

**Issue by Leonardo-DGS** [IntellectualSites/PlotSquared#2501]
**[REQUIRED] Spigot/Paper Version Number:**
This server is running Paper version git-Paper-186 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**[REQUIRED] Minecraft Version Number:** 1.14.4

**PlotSquared Version:** 4.358

**[REQUIRED] Description of the problem:**
When you execute /plot setowner without arguments, it will say that the player is not found instead of sending the command usage.

**[REQUIRED] How to replicate:** 
1. Execute /plot setowner in a plot

**Comment by MattBDev** [comment]
You barely followed the template. You can't just pick and choose what information to give us. Provide a debug paste or I will close this issue in 2 hours.

**Comment by Leomixer17** [comment]
@MattBDev That informations aren't needed.

**Comment by AeSix** [comment]
closing due to refusal to provide required information

**Comment by Leomixer17** [comment]
@AeSix The bug will remain even if you ignore my report

**Comment by Draycia** [comment]
You better listen to them and provide the information then :D

**Comment by Sauilitired** [comment]
Listen. Most of us don’t actually use the plugin ourselves, we only develop it. Bugs are going to impact the users, and all we ask from the users is that they help us track down the cause by providing some (quite minimal) information. You didn’t even include the PlotSquared version. In this specific case it might not be necessary, as we could hunt it down anyway. But there has to be some consistency in here, as the issue tracker would be a bloody mess otherwise, and the project is hard to maintain as is.

Anyway, the issue is the logic in https://github.com/IntellectualSites/PlotSquared/blob/breaking/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/commands/Owner.java

**Comment by AeSix** [comment]
@Leomixer17 
If you were able to understand the number of times people have reported broken things, bugs, exploits, etc for a specific server version, only to come to find out that they're using an old, outdated, not-intended-for-that-version of PlotSquared, you'd understand why we need the information that is required.

**Comment by Leomixer17** [comment]
@AeSix The PlotSquared version is 4.358
