### ISSUE TITLE
PlotSquared Generator importing World wrong

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2604]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):

https://athion.net/ISPaster/paste/view/4195bcb93071451f90917f40954b27f7

### Server type:
**select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [x] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-230 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-S
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit *version*: WorldEdit version 7.0.1;61bc012

### Description of the problem:

I have a original (Self Build) Plotworld with own roads and want to share it with my developer.
On my original server, the world is great and intact. But now the problem if i copy the world to another server and importing it using multiverse with the command /mv import plotworld NORMAL -g PlotSquared the world was imported but after a few plot the world go into a (Default) Plotworld.
I mean that was a multiverse issue but i tested it with some versions of MultiVerse and other World plugins. On all tests i have the same problem. Than i unistalled all world generators and unsing the default bukkit.yml to import my world with
`worlds:
  plotworld:
     generator: PlotSquared`

But the world was imported wrong. 

Here a screenshot of the Problem: https://i.imgur.com/yXXdeub.png

I think its a Problem of the PlotSquared build in Generator because the issue is still present in Bukkits Default world System and few diffrent other World Managers like MultiWorld
         

### How to replicate:

Import a existing plotworld into a fresh server.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

MultiVerse, PlotSquared, WorldEdit

### Relevant console output, log lines, and/or screenshots:

https://i.imgur.com/yXXdeub.png
### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by Resi23** [comment]
Have you copy the schematic Folder in PlotSquared Folder to new server?

**Comment by N0tMyFaultOG** [comment]
> Here a screenshot of the Problem: https://i.imgur.com/yXXdeub.png

You cannot import the world into an existing world and override the settings. That will not work and produce the screenshot above.

**Comment by AeSix** [comment]
It is best if you manually add the PS world as a second world to the server that will be it's new home.  This can be tedious.  Being that it is possible, easy enough, and there is not a lot of need for people to do this (maybe 0.01% of users would do this in a given month?), there is no reason for the developers to attempt to correct this.  

However, I will be making a feature suggestion for export/import which would package up the entire world's worth of data and incorporate that data into a different server, because the devs should have a proper opportunity to shoot it down (or possibly take it on)

With that, this is a user/admin issue, not a bug in PlotSquared.  Follow the instructions on the wiki for creating a new world using only PlotSquared, and then replace that new world's schems, configs, etc with the world you want to use.  If you have trouble with that, you can re-open this ticket and update it with that information.

**Comment by DevJoey** [comment]
No! It was a already existing World that i will import in a new server. You have missunderstand my issue. The problem is, a world gets imported wrong.

**Comment by N0tMyFaultOG** [comment]
>You cannot import the world into an existing world and override the settings. That will not work and produce the screenshot above.
>> No! It was a already existing World that i will import in a new server. You have missunderstand my issue. The problem is, a world gets imported wrong.

You will need to make a void world or something similar to import the existing world. Overriding a plot world (like in your screenshot) will not work.

**Comment by AeSix** [comment]
BEFORE DOING ANYTHING - MAKE A FULL BACKUP OF THE SERVER YOU ARE IMPORTING TO, INCLUDING THE DATABASE!!! Set this aside and hope you do not need to revert back to it!

The easiest way I know to do something like this is to create a new world following the wiki - make sure it's the same name as the world you're importing.  Go to that new world, and generate some chunks. 

Then, shut off the server, and follow these steps:
[1]  Go into plugins/PlotSquared/worlds.yml - verify that the world you just created has exactly the same settings as the one you're importing.  
[2] Go into the server's world folder that was created, and delete everything.  MAKE SURE THIS IS THE NEW, UNUSED WORLD!!!  
[3] Copy all of the files from the old world that you are importing into that directory. 

If you are using MySQL/MariaDB for your database, and have a proper SQL backup of the data you're importing, then now is the time to import that data into your MySQL/mDB server.  
If you are using a flat file, then make sure to put it where it belongs.

You should now be able to start up the server, and go into that world - and if you have done everything properly, the plot owner info will be available.  If you did not, or do not have the database backup, or if you are changing from offline to online UUIDs (or vice versa), then you will need to assign every plot manually.  If you have only a handful of plots, no an issue... otherwise it's kind of impossible.  

This is literally the only way I know of importing an existing plot world into another server.  And if you have naming collisions (the world to be imported has the same name as any world already on the server) - then you're not going to be able to.  At that point, creating a new server and following the above steps for that server's *only* world, it will work.  But there's a lot that can go wrong, and patience is more than a virtue.  You may have to try two or three times to get everything right. 

Good luck.
