### ISSUE TITLE
Plot biome only partially sets the biome

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#2606]
# NOTICE: 
```diff
! PlotSquared for Minecraft Java Edition versions between 1.7 through to 1.12.2 are considered
! legacy, and will receive limited to no support. Please consider upgrading to 1.13+ for
! future support.  Plugins exist for 1.13+ which bring back behaviors found in 1.8.8
! All versions of PlotSquared for Sponge and Nukkit(X) will recieve limited to no support
! due to lack of developer interest and time. Additionally, NukkitX has not had feature
! updates since the Better Together, which prevents some PlotSquared features from ever
! functioning.  Contributions are always welcome however!
```

**Feature requests & Suggestions are to be submitted at the [PlotSquared Suggestions tracker](https://github.com/IntellectualSites/PlotSquaredSuggestions)**

**Code contributions are to be done through [PRs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), tagging the specific issue ticket(s) if applicable.**

**[DISCORD INVITE LINK](https://discord.gg/cSMxtGn)** and please, for the love of the little sanity we have left, use the correct channels!

# BUG REPORT TEMPLATE:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):
worlds.yml: https://pastebin.com/4QUjDJHn
settings.yml https://pastebin.com/JQu1Vraj
PlotSquared version: PlotSquared-4.411

### Server type:
**select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [X] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

``` git-Paper-226 (MC: 1.14.4) ```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [X] WorldEdit *version*: worldedit-bukkit-7.0.1

### Description of the problem:
Using **/plot setbiome snowy_taiga** for example will not set the biome for the entire plot, it seems to be setting the biome in loaded chunks only:

Default plot which is forest:
![image](https://user-images.githubusercontent.com/10485646/69665707-d85d2f80-1082-11ea-8b51-ee9156058844.png)

After setting the plot biome to snowy_taiga:
![image](https://user-images.githubusercontent.com/10485646/69665868-23774280-1083-11ea-94ad-3ca109050cf7.png)

### How to replicate:
Go to a plot you already own and use /plot setbiome [biome]

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by MattBDev** [comment]
Did you make sure to log off and log back on? The client can't update biomes properly.

**Comment by SecretlyJealous** [comment]
Didn't fix the issue and restarting doesn't fix it either.
![image](https://user-images.githubusercontent.com/10485646/69680649-73fe9800-10a3-11ea-9e4a-5cb8d29c4189.png)

**Comment by traksag** [comment]
I did some testing in Spigot 1.14.4 (git-Spigot-56f8471-6567017). This problem occurs chiefly when not all the chunks of the plot you are trying to set the biome of, are generated. Oddly enough, if you fly around to generate the chunks and then immediately try to set the biome, not all chunks are updated… perhaps the is-chunk-generated detection isn't 100% sound.

Either way, in the code the offender is [here](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/object/Plot.java#L954). Setting the 'force' parameter to 'true' fixes this issue on Spigot.

I also did some testing on Paper 1.14.4 (git-Paper-237). Again, similar problems occur. However, the fix I mentioned before doesn't work here. This is probably due to the fact that the offending chunk-load call does its job async, and hence the program may attempt to set the biome before the actual chunk is generated and loaded. This can be fixed by either loading the chunk synchronously or by updating the biome after the chunk has been loaded (e.g. with `thenRun(…)`). Both these solutions should also fix the issue on Spigot.

I would submit a pull request, but I'm not sure which is preferable: sync loading or async loading combined with `thenRun(…)`. The former is trivial to implement (although a sync-chunk-load method in ChunkManager may be necessary) and will work properly with the current system of allocating time in `chunkTask(…)`. For the latter, async option I worry that setting the biome synchronously in `thenRun(…)` may consume too much time per tick across all the different chunk loads (we have no control over the tick `thenRun(…)` is completed); although this worry may be unwarranted/unimportant.

If you want, I could write a pull request to fix this issue if my doubts are addressed.

**Comment by Tiippex** [comment]
Just to keep that updated here:
The problem exists in PlotSquared 4.489 with git-Paper-143 (1.15.2)

**Comment by SecretlyJealous** [comment]
This is still an issue on PlotSquared 5.11.0
Using git-Paper-280 (MC: 1.15.2)

Console also spams this:
> [17:31:12 INFO]: [Biome Operation] Loading chunk took: 0
> [17:31:12 INFO]: [Biome Operation] Unloading chunk took: 0
> [17:31:12 INFO]: [Biome Operation] Loading chunk took: 0
> [17:31:12 INFO]: [Biome Operation] Unloading chunk took: 0
> [17:31:12 INFO]: [Biome Operation] Loading chunk took: 0
> [17:31:12 INFO]: [Biome Operation] Unloading chunk took: 0
> [17:31:12 INFO]: [Biome Operation] Loading chunk took: 0
> [17:31:12 INFO]: [Biome Operation] Unloading chunk took: 0
> [17:31:12 INFO]: [Biome Operation] Loading chunk took: 0
> [17:31:12 INFO]: [Biome Operation] Unloading chunk took: 0
> [17:31:12 INFO]: [Biome Operation] Loading chunk took: 0
> [17:31:13 INFO]: [Biome Operation] Unloading chunk took: 0

**Comment by Sauilitired** [comment]
You can disable the console spam by disabling debug mode in settings.yml.

**Comment by Sauilitired** [comment]
Fixed.
