### ISSUE TITLE
Crops not growing

### ISSUE THREAD

**Issue by 83y** [IntellectualSites/PlotSquared#2664]
Debug paste link: https://www.athion.net/ISPaster/paste/view/af5cdd764ca44b3297dcd375550a8343

Spigot/Paper Version Number: Spigot git-Spigot-79a30d7-acbc348 (MC: 1.12.2)

Minecraft Version Number: 1.12.2

Description of the problem: crops like sugar cane, cactus etc. wont grow (yes i increased the tickspeed) when someone first joins the server and claims a plot and tries to grow crops, they wont grow. But if i were to stop the server and start it again they will grow again. And i dont want to have to stop the server everytime to make crops grow. I managed to fix the problem with growing crops like Wheat, Carrots and Potato's by placing a block above them to update the chunk.

Plugins being used on the server: Listed in the debug

Checklist:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
If this issue persists when updating to a supported version (1.3.2, 1.14.4, 1.15.x) of Spigot or Paper, please re-open the ticket with a debugpaste from the new version.  1.12.2 and older are considered legacy and will receive limited to no support.   If this issue persists in PlotSquared 4.4xx on Spigot 1.15.1, the developers will look into it.  However, please ensure that no other plugin or server configuration setting is interfering.

**Comment by 83y** [comment]
That's a bit useless

**Comment by 83y** [comment]
That's useless

**Comment by AeSix** [comment]
It's not useless.  You can either use supported software, or not.  You're not using supported software.  So, you're not getting support.  If you want support, then use supported software.

**Comment by 83y** [comment]
Literally nobody uses 1.13+ and why release a version that doesn't work (1.12), pointless...

**Comment by N0tMyFaultOG** [comment]
> Literally nobody uses 1.13+ and why release a version that doesn't work (1.12), pointless...

You are right. Almost nobody uses 1.13 anymore, barely 4.4%. Within the release of newer versions of Minecraft, we are most likely abandoning 1.13 as well, since more than 50% of Minecraft servers are either using 1.14 or 1.15. Almost 60% of all PlotSquared users are using 1.14 and 1.15, therefore it doesn't make much sense anymore to support older versions for free.
Since this is a hobby project for the majority of us and we are looking into the future and not the past, we are focusing on newer versions. At the moment you start paying for support, we will consider supporting legacy versions, but until then, the support for versions prior to 1.13 has been dropped.
