### ISSUE TITLE
 Problem with Merging Plots 

### ISSUE THREAD

**Issue by Ashracx** [IntellectualSites/PlotSquared#2999]
### Server Implementation

Purpur

### Server Version

1.16.5

### Describe the bug

If i merge with my face to the east direction all of my plots will merge together.
But if i type /p merge, in all other directions (north, west or south) every time only 1 plot will merge together.

For testing i have installed a new Server with:
paper-1.16.4-366
LuckPerms 5.2.35
Multiverse-Core 4.2.2
FastAsyncWorldEdit 1.16 492
PlotSquared 5.13.10

### To Reproduce

type /p merge in any direction

### Expected behaviour

All plots in the dirction ive looked should be merged

### Screenshots / Videos

https://www.youtube.com/watch?v=8s3Xk3NZluw

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/7c60dfe24f3e4505a08a0392759ac07e

### PlotSquared Version

5.13.11 Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by Ashracx** [comment]
Same problem with 6.0.0-Snaphot

**Comment by OneLiteFeather** [comment]
![grafik](https://user-images.githubusercontent.com/77929075/233804470-034726d1-7e40-4b6f-b4a4-66a3121c5846.png)
It doesn't do that as shown in your youtube video with Plotsquared v6.11.1, Paper 1.19.4 (516) and FAWE-401 anymore
Looks like this issue is solved for now. If it is still/again occuring in latest Plotsquared release let us know.
