### ISSUE TITLE
PlayerAutoPlotEvent plot variable is null 

### ISSUE THREAD

**Issue by MeowRay** [IntellectualSites/PlotSquared#3072]
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

Executing the /p claim command will not trigger PlayerClaimPlotEvent, but it will trigger PlayerAutoPlotEvent, and the plot variable is null 

### To Reproduce

1. listener event
2. enter command /p claim 

### Expected behaviour

fix

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/29674595/119792490-51537680-bf08-11eb-8478-3273217b150d.png)
![image](https://user-images.githubusercontent.com/29674595/119792520-56b0c100-bf08-11eb-9066-7df2ed6176b6.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/0b35c4d8798f4bae84146238fc53ab60

### PlotSquared Version

5.13.11-Premium

### Checklist

- [x] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Tested on v6, I'm unable to replicate that.

![](https://i.imgur.com/p417wDa.png)

> and the plot variable is null

If no schematic is set or it's for whatever reason not able to paste it, the schematic part will return null but that does not invalidate the entire call.

**Comment by MeowRay** [comment]
> Tested on v6, I'm unable to replicate that.
> 
> ![](https://camo.githubusercontent.com/fc941c9c731e877fb6c94519a4f55d6ea9aaed6d100e23bff8d3903ed9f1d482/68747470733a2f2f692e696d6775722e636f6d2f703431377744612e706e67)
> 
> > and the plot variable is null
> 
> If no schematic is set or it's for whatever reason not able to paste it, the schematic part will return null but that does not invalidate the entire call.

v6 version? Where can I download this?

**Comment by NotMyFault** [comment]
> > Tested on v6, I'm unable to replicate that.
> > ![](https://camo.githubusercontent.com/fc941c9c731e877fb6c94519a4f55d6ea9aaed6d100e23bff8d3903ed9f1d482/68747470733a2f2f692e696d6775722e636f6d2f703431377744612e706e67)
> > > and the plot variable is null
> > 
> > 
> > If no schematic is set or it's for whatever reason not able to paste it, the schematic part will return null but that does not invalidate the entire call.
> 
> v6 version? Where can I download this?

Nowhere. It's the next major release version but still work in progress. If you want to do your own testing, you need to compile it from scatch.

**Comment by MeowRay** [comment]
> > > Tested on v6, I'm unable to replicate that.
> > > ![](https://camo.githubusercontent.com/fc941c9c731e877fb6c94519a4f55d6ea9aaed6d100e23bff8d3903ed9f1d482/68747470733a2f2f692e696d6775722e636f6d2f703431377744612e706e67)
> > > > and the plot variable is null
> > > 
> > > 
> > > If no schematic is set or it's for whatever reason not able to paste it, the schematic part will return null but that does not invalidate the entire call.
> > 
> > 
> > v6 version? Where can I download this?
> 
> Nowhere. It's the next major release version but still work in progress. If you want to do your own testing, you need to compile it from scatch.

I re-tested, PlayerClaimPlotEvent works normally, but the variable plot of executing /p auto PlayerAutoPlotEvent is still null (plot is successfully claimed)

**Comment by dordsor21** [comment]
This is by design. The event is fired before the plot is chosen by the plugin (allowing for the auto to bypass plot limits, auto size limits, etc.). If you're intending to use the event similarly to the PlayerClaimPlotEvent there is currently not an equivalent, thus it would be useful if you could alter the initial issue to describe what you're needing the plot for, to best implement an event when the plot has been chosen.

**Comment by AerWyn81** [comment]
Hi, I have a similar "issue" but I think I'm not doing it correctly.

I want to get the Plot object to use it later when a player uses the /plot auto command. The problem is that the plot object in the PlayerAutoPlotEvent is null by design. There is another event that actually has a plot object PlayerClaimPlotEvent but not triggered when using /plot auto (seem's logic because triggered by /plot claim but i wont let players use this command).
How can I get the plot object back when a player uses the /plot auto command?

The question may seem stupid but if it can be useful to other people...
