### ISSUE TITLE
Sethome sometimes causes a teleport under the plot after upgrading your world

### ISSUE THREAD

**Issue by EscolarProgramming** [IntellectualSites/PlotSquared#3536]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

If you set your plot home it can happen that after teleporting home you either fly through the plot (as if you had GM3 without flying), or you spawn directly under the bedrock. Putting the plot home in the air helps sometimes, but not always.

### To Reproduce

1. Use /p sethome on your plot
2. Use /p home to go to your plot
3. Now it can happen that you fly through your plot 

### Expected behaviour

You shouldn't fly through the plot, instead you should spawn at the right location

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/89cf700752fe41c0a01031f5daed4d47

### PlotSquared Version

PlotSquared-6.6.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
I'd recommend to update Paper and Fawe first. I've cloned your plotworld setup on a fresh server, where I'm unable to replicate the issue based on the steps provided. Where did you set the home location to? Any specific block?

**Comment by ofunny** [comment]
This only happens if the plot home position has been set manually via "sethome", all these locations turned to a negative y for me after I updated to the 6.6.1 – I fixed it for me by bulk updating the MySQL(MariaDB) table row "position" in the plot_settings table to "default" for all entries.

**Comment by ofunny** [comment]
Okay, after further testing it also happens to me for newly created home locations via "/plot sethome". 
"/p home" will teleport the player into the void if the plot has not been extended to minus 64 yet (air blocks below 0). 

Since it works on newly created plots with blocks (not air) starting at -64 it maybe is related to the method PS determines the teleport location? The values within the location row are not equal to real MC world coordinates so I assume there is some logic to create them on tp (kinda weird, why not caching real coordinates …).

**Comment by EscolarProgramming** [comment]
Can you already say when the bug will be fixed? Currently we can not use the 6.6 because of the bug, and the 6.5 makes it difficult, because we can no longer delete plots because of the timer. A fawe with which it is possible under PS 6.5, there is currently also not for the 1.18.2, not even the old versions

**Comment by JLyne** [comment]
Ran into this issue myself and had a look into it. [The problem](https://github.com/IntellectualSites/PlotSquared/blob/25095f4546f1748c32b9959c150431c3ec2513b3/Core/src/main/java/com/plotsquared/core/command/SetHome.java#L60) is that `sethome` isn't using the Y for the bottom of the build area when saving the relative spawn position. [getHome](https://github.com/IntellectualSites/PlotSquared/blob/42bf4135281f048ebca0eb2966568bfe01f1611d/Core/src/main/java/com/plotsquared/core/plot/Plot.java#L1456) however does use the bottom Y, which means that a world extending to Y=-64 will teleport players 64 blocks below the saved home position when visiting plots.

This issue is more obvious on plots made before the `min_gen_height` was set to -64, as they will have air at Y<0. New plots with solid blocks at that location will cause `getHome` to use `getHighestBlock` instead, which avoids the below world problem but will cause home positions inside buildings etc to teleport players above them.

**Comment by DeEthria** [comment]
New PlotSquared Version - Bug is still there

**Comment by NotMyFault** [comment]
> New PlotSquared Version - Bug is still there

That is about to be expected, considering this issue is not closed yet.
