### ISSUE TITLE
Crash Exploit

### ISSUE THREAD

**Issue by AlekseyTitov99** [IntellectualSites/PlotSquared#3964]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

When you run these commands the server crashes:

- /plot 10000,900000 claim
- /plot auto 50000,1000

### To Reproduce

When you run these commands the server crashes:

- /plot 10000,900000 claim
- /plot auto 50000,1000

### Expected behaviour

Not crash my server

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/6637594d3d17419996c642f33c33711f

### PlotSquared Version

plotsquared-6.11.0-premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
The second command is not really a crash exploit and requires a permission you wouldn't just give anyone. By executing the second command you try to claim 50000000 plots, where the server has to calculate a position for that to not interfere with other plots as well as execute a huge amount of plot modifications and database writes. 

If just the first command crashes the server as well - that might be due to slow chunk loading / chunk generation or in general slow I/O speed. 


Either way, you said the server crashes but haven't event added the error / crash log?

**Comment by NotMyFault** [comment]
As noted correctly by Pierre, separate permissions guard these commands. Assigning those permissions leads to the described behavior.
I recommend unassigning the permissions if you don't want players to use them.
