### ISSUE TITLE
MySQL error when claiming a plot

### ISSUE THREAD

**Issue by renickbuettner** [IntellectualSites/PlotSquared#4168]
### Server Implementation

Spigot

### Server Version

1.20.1

### Describe the bug

MySQL Exception

### To Reproduce

1. Plot Claim

### Expected behaviour

Not seeing an exception :-)

### Error log (if applicable)

https://gist.renick.io/?4755aedf10af38a4#5U1iGp7qvL9R5F76LUXUWGvaoxtttsnWh3dCpSsLdnL5

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/e4da37337abb42dd9312cdbcad154c38

### PlotSquared Version

7.0.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
I believe that this is/was caused by having a very outdated sqlite driver installed when setting up the database, and is not an issue with P2. The fix is either to remake the database (delete and allow 2P to regenerate it) or to alter the table `<prefix>plot_settings` and set the default value of the position field to `DEFAULT`
