### ISSUE TITLE
BeaconEffectEvent Error Spam

### ISSUE THREAD

**Issue by Zapnerd** [IntellectualSites/PlotSquared#4410]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

I'm using a plugin WildLoaders that will keep chunks loaded, this is how players got beacons on my server. When a player placed the WildLoader, this started spamming for a specific UUID. I can't find the UUID though, so I'm thinking it must be a bedrock player. But either way its litterally sending this message 10 times a second, infinitely spamming.

### To Reproduce

Add WildLoaders, I believe you need a bedrock player to place a Beacon/Chunk Loader, log off maybe? And its spamming.

### Expected behaviour

Add a check to not allow the error to spam, thanks.

### Error log (if applicable)

https://gist.github.com/Zapnerd/a862fd20cb5f49d7132c93e9eb7a9221

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/a7030f568b92472191deb8a266d41241

### PlotSquared Version

7.3.8 Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
I don't really see the issue with PlotSquared here. Rather Floodgate or Pufferfish. It seems like the BeaconEffectEvent is called on a player that is not online anymore based on the Bukkit API return value. I doubt that logout happens during one tick - and either way, the event is handled synchronously and no state change might occur.
Either the event is called on an offline player by Pufferfish or Floodgate does not return the correct online state for the player (Tho I'd rather tend to the first)

**Comment by OneLiteFeather** [comment]
Well your Chunkloader is implementing a fake player which is actually a minecraft player. Try to build a chunkloader with a different plugin that doesn't emulate a player (which is in the range of true player UUIDs, this is dangerous as there might be really a player with the UUID) or build a vanilla chunkloader, then it will work. The issue lies within your WildLoaders plugin. I've seen this error before here somewhere with a Beacon Chunkloader Plugin.
