### ISSUE TITLE
Version 2.12.18 not working in Spigot 1.8.7

### ISSUE THREAD

**Issue by dvargas135** [IntellectualSites/PlotSquared#463]
Error log when I try to claim a plot:
http://pastebin.com/rAiUkDik

**Comment by Sauilitired** [comment]
Released a reverse update, that will revert back to the latest stable one (2.12.15). For future reference, please do not post ratings with bugs as the reason. It really puts me off, and whilst I cannot speak for @boy0001 I'm sure he doesn't feel so good about it either. We do this in our spare time, and to rate the plugin 1/5 just because something isn't working as intended, doesn't really provide the effect that you wanted.

The issue tracker is here for a reason, and having it means that the plugins reputation and listing in the resource section doesn't have to be ruined, because one bug slipped past our testing.
