### ISSUE TITLE
Chunks are void for ~1/10 plots for players that tp to them

### ISSUE THREAD

**Issue by andrewgazelka** [IntellectualSites/PlotSquared#551]
Pretty much having the same issue as this guy: https://www.spigotmc.org/threads/problem-bug-weird-chunk-errors.60164/

**Comment by boy0001** [comment]
Necessarily a PlotSquared issue?

**Comment by frizzbee30** [comment]
we have had an issue similar, just moved to plotsquared and put the trim on,auto unload on, chunks disappered with the unload (fair enough) took it off. However, getting the error in other worlds where chunks just don't load, and they were there before.

**Comment by boy0001** [comment]
Well since I can't really replicate this, want to show me on your server or something?

**Comment by frizzbee30** [comment]
We have fixed it by disabling the auto unload, that seem's to have been a bit too aggressive. It did also seem to be tied into the server updating the client as sometimes, but not always, logging out then back in helped. However, the server looked like an attack of the jack in the box's!  Hence we disabled it :)  

So unfortunately we can't demonstrate, or the players we have would just not return,as it caused some serious annoyance issues, especially when falling into the void and losing a full inventory. 

Since disabling this we have had no issues and think the plugin is beyond amazing!

**Comment by boy0001** [comment]
@UltraX3 didn't have auto-unload set to true, so I thought it might have been a recurring issue. Yeah, that's fine not wanting to enable it again

**Comment by PhanaticD** [comment]
I wanted to try the faster worldedit and auto-trim so I enabled the chunk processor and am getting this issues

relevant config section: http://pastebin.com/8EETLu2a

some screenshots:
https://gyazo.com/dd38023805a4e049dbfad9b110d1b0d5
https://gyazo.com/0e52d01d8ae83d83e5f0404d60e9ead2

**Comment by robertshady** [comment]
I had this problem as well, had 2 out of the 3 players in the world falling into the void.  I restarted the server and logged back in after about an hour or so and everything was working fine.. Didn't change anything in the config, so weird.

**Comment by BlackBeltPanda** [comment]
Also having this issue in 1.12. I don't have auto-trim enabled but I do have the chunk-processor enabled.

**Comment by frizzbee30** [comment]
we have had no further issues since disabling auto unload, and currently on 1.12.2  :)

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
