### ISSUE TITLE
Plot claim schematic.

### ISSUE THREAD

**Issue by soulofwolf1** [IntellectualSites/PlotSquared#614]
When having a plot claim schematic the first time a plot is claimed it pastes in fine, but if a plot is not cleared when unclaimed and it is claimed again and pasted in again it pastes in from the y of the current ground level of the plot, instead of pasting in from the plot height set in the config.

**Comment by boy0001** [comment]
1.) If you want it to paste at the same height each time, you need to have the schematic 256 blocks tall.
2.) Or if you just want it part of world generation (i.e. it will be in unclaimed plots as well), you could put the schematic in the following location: `plugins/PlotSquared/schematics/GEN_ROAD_SCHEMATIC/<world>/plot.schematic`
3.) You also should be using plot delete rather than unclaim.
