### ISSUE TITLE
Login Bug

### ISSUE THREAD

**Issue by sojiro7** [IntellectualSites/PlotSquared#664]
Hello,

When I log in the server with a regular account that has player permissions, everything works perfectly. However, if I leave the server and log back again with the same account, everything stops working. This happens for all players, except OPS. I have check permissions and they are properly configured. When I log in for the second time, that nothing works, I get no errors in console, no error in-game. When I type any P2 commands, the chat just stays blank, no blank line or error, just nothing.

Any help would be appreciated.

Johann

**Comment by sojiro7** [comment]
Well, after wasting so many hours. I realize is your last update that breaks everything. I downgraded and now its working.

**Comment by TagCraftMC** [comment]
Yup, just ran into the same problem trying to work out what it was since it's seems to happen randomly to people. I have even tried forcing the command via sudo/force and no such luck.
@boy0001 Ill dump what info we have below for you.
Latest.log (Effected user is _Annonymous_): 
Settings: http://hastebin.com/tolikuweja
/plot debugpaste: http://hastebin.com/gaceqavigo
Pex Debug of effected user: http://pastebin.com/exiiV0Eq
/plot debugexec seen: https://i.gyazo.com/1bba3c0394f74a3831f478655dbca094.png

Let me know if you require more info or sacrifices.
Thanks.
