### ISSUE TITLE
Add compatibility for GP when MultiVerse is not used

### ISSUE THREAD

**Issue by RoboMWM** [IntellectualSites/PlotSquared#732]
GriefPrevention automatically removes worlds that are not loaded  from its config.yml when it enables - is it possible to have PlotSquared load during onEnable instead of after (maybe add an option in settings.yml)? (Also might potentially mitigate a theoretical possibility when someone joins right at the server starts, spawning in another world since PlotSquared's world wasn't loaded quite yet.)

Also see https://www.spigotmc.org/threads/griefprevention.35615/page-69#post-1133212

**Comment by boy0001** [comment]
Can't really do this. Worlds are created with various settings such as seed, spawn options etc.. World management plugins generally have all of this configurable, and if PlotSquared creates the world, these settings are ignored.

PlotSquared is not meant to be a complete replacement for MultiVerse, and there are other multi world plugins out there. It as intended that PlotSquared will only create the world if none are present. 

Also, the world is created as soon as the bukkit task scheduler is initialized, which is before anyone can login since it's all done on a single thread.

Solution: Tell GP devs that it's a stupid feature, or install a world management plugin.
