### ISSUE TITLE
Crash related to PlotSquared?

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#745]
Log: http://pastebin.com/ptmr3QjG
Log: http://pastebin.com/smaz825Y
I suspect it's something to do with "com.intellectualcrafters.plot.database.SQLManager$3.run(SQLManager.java:229)" judging by the line causing the issue but I'm not too sure.

**Comment by SecretlyJealous** [comment]
Crash on one of my other servers:

Log: http://pastebin.com/QmRGf9qv
Crash report: http://pastebin.com/JAaz4GzJ

**Comment by boy0001** [comment]
The PlotSquared SQLManager is on a another thread. In the case of the server hanging, you want to look at what's happening on the `server thread`.

In your case however, it's not directly caused by any plugins. All three crashes have completely different stacktraces on the main thread of only nms. The last one could possibly be someone spamming entities. The first two at least are fairly ordinary.

Maybe try updating spigot, and do a timings to see if anything is slowing down the server.

**Comment by Sauilitired** [comment]
**Outdated Issue:** No further information provided, assuming to be fixed or unrelated
