### ISSUE TITLE
Wont' let anyone use /plots

### ISSUE THREAD

**Issue by dankeykang12** [IntellectualSites/PlotSquared#755]
Hello we can't get the plugin to allow all players to use /plots, any ideas

**Comment by manuelgu** [comment]
Whats your permission setup?
What is the message players are getting when executing the commands?

[This](https://github.com/IntellectualSites/PlotSquared/wiki/Commands-and-Permissions#base-permissions) might help you.

**Comment by dankeykang12** [comment]
"you do not have permission to do this"
 were using the default group plots.use and plots.permpack.basic

**Comment by manuelgu** [comment]
Sounds like a misconfiguration of your permissions. Do you use PEX?

**Comment by dankeykang12** [comment]
Yes we use PEX

**Comment by dankeykang12** [comment]
Hello?

**Comment by lilacorn** [comment]
I use group manager here and no problems, might have to add individual
permissions not the group cluster kind, like one for claim, tp n etc not
just allonegroup.permission if you know what i mean. I had to add every
single permission node that is listed in the group cluster.

On Fri, Nov 27, 2015 at 3:13 PM, dankeykang12 <notifications@github.com>
wrote:

> Hello?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IntellectualSites/PlotSquared/issues/755#issuecomment-160218957>
> .
>



-- 
Michelle
Web: http://lilacorn.net

**Comment by Orenthion** [comment]
Please use http://pastebin.com/ to upload your permissions.yml from the PermissionsEx plugin folder. That way we can find the error.

**Comment by boy0001** [comment]
`"you do not have permission to do this"` - This message is not from PlotSquared, nor the default bukkit message. Another plugin is likely preventing the action. (Assuming you provided an accurate quote of the message)

PlotSquared would display `"You are lacking the permission node 'plots.use'"`, but only if you specifically negated the perm, since for a while now `plots.use` has defaulted to true.

For future reference, a `/plot debugpaste` will help us resolve your issue.
