### ISSUE TITLE
Plot info should show expiration date

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#852]
On my server I've set-up my expire manager to clear a plot if the owner of the plot has not come online in the past 30 days, it would be really useful if /plot info showed the date of expiration. For example if yesterday was 02/01/16 and the user has not come on the server since, it should show this in plot info Expiration: 03/01/16 and should automatically update when the user joins the server.

**Comment by CoolLord22** [comment]
That's an awesome idea!

**Comment by LXsource** [comment]
This should be added.

**Comment by MattBDev** [comment]
I plan on adding this after the plugin cleanup.

**Comment by LXsource** [comment]
excellent

**Comment by boy0001** [comment]
There are debug commands related to plot expiry. (`/plot debugexec <analyze|calibrate-analysis|stop-expire|update-expired|show-expired|seen>`). I have no issue improving upon these debug commands, but I don't think it needs to be shown in plot info since it is for server administrators. 

Showing the date to players without them understanding how it works might be misleading. For instance; there may also be a complexity threshold, which is well beyond what ordinary players would need to understand.

**Comment by MattBDev** [comment]
It will only be shown when expired plots are enabled and I am thinking about adding a config for it,
