### ISSUE TITLE
Schematic save/paste problem 

### ISSUE THREAD

**Issue by Ksnz** [IntellectualSites/PlotSquared#907]
When i save and then paste schematic it pastes over floor without replacing it.
![2016-02-28_18 54 45](https://cloud.githubusercontent.com/assets/3342111/13380154/fd26cdf6-de4c-11e5-8aed-9b4647c0d858.png)

My config
`    plot:`
`      height: 2`
`      size: 48`
`      filling:`
`      - '159:15'`
`      floor:`
`      - '9'`
`      bedrock: true`

**Comment by MattBDev** [comment]
Please folow the issue template in the future. Provide a '/plot debugpaste' for further assistance. If more information is not provided within 24 hours, this issue will be closed.

**Comment by boy0001** [comment]
@Ksnz That's sort of a design flaw I guess since the behavior is intentional.

The schematic system is separate from the plot generation, so regardless of what generator you use, it   will paste it on top. A possible workaround is to make the schematic 256 blocks tall (just have everything else air)

**Comment by Ksnz** [comment]
@MattBDev http://hastebin.com/bajoqilawu

Also I'm going to use API for pasting and it would be great to have method for pasting without offset on y axis here
https://github.com/IntellectualSites/PlotSquared/blob/master/Core/src/main/java/com/intellectualcrafters/plot/util/SchematicHandler.java#L109

**Comment by boy0001** [comment]
Added
