### ISSUE TITLE
Error with 1.9 on Jenkins Build #5

### ISSUE THREAD

**Issue by astr1al** [IntellectualSites/PlotSquared#941]
http://pastebin.com/RF3jAGCt

**Just a startup error.**
Running WorldGuard v6.1.2-SNAPSHOT;1652-c9b8e9f
Server is running CraftBukkit version git-Spigot-bc01c3a-0cd6711 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

**Comment by MattBDev** [comment]
1. Please do not delete the Issue Template. It said not to yet you did it anyways.
2. Spigot 1.9 is very unstable at the moment. You need to make sure you are running BuildTools everyday, twice a day.
3. This issue seems to be caused by WorldEdit.
4. Don't use Jenkins builds until @Sauilitired fixes our CI and tells us where the proper builds are.
